// ─── Gao Social V3 — Seed Data ────────────────────────────────────────────
// Demo city: Dallas, TX (32.7767, -96.7970)
// RULE: Empty map is forbidden. These minimums are hard requirements.

// ─── Businesses (20) ──────────────────────────────────────────────────────

export const SEED_BUSINESSES = [
  { id: 'biz_001', name: 'Glow Nail Studio', category: 'beauty', description: 'Premium nail care and spa services in downtown Dallas.', location_lat: 32.7767, location_lng: -96.7970, trust_score: 94, trust_level: 'highly_trusted', badges: ['verified_business', 'top_rated'], proof_count: 85, rating_avg: 4.9, rating_count: 85, open_now: true, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['09:00-18:00'], tue: ['09:00-18:00'], wed: ['09:00-18:00'], thu: ['09:00-18:00'], fri: ['09:00-19:00'], sat: ['10:00-17:00'], sun: [] } },
  { id: 'biz_002', name: 'Deep Ellum Coffee', category: 'food', description: 'Artisan coffee roasters since 2018.', location_lat: 32.7835, location_lng: -96.7838, trust_score: 87, trust_level: 'highly_trusted', badges: ['verified_business'], proof_count: 62, rating_avg: 4.7, rating_count: 62, open_now: true, booking_enabled: false, payment_enabled: true, status: 'active', hours: { mon: ['06:00-20:00'], tue: ['06:00-20:00'], wed: ['06:00-20:00'], thu: ['06:00-20:00'], fri: ['06:00-21:00'], sat: ['07:00-21:00'], sun: ['07:00-18:00'] } },
  { id: 'biz_003', name: 'Iron Temple Fitness', category: 'fitness', description: '24/7 gym with personal training.', location_lat: 32.7801, location_lng: -96.8005, trust_score: 78, trust_level: 'trusted', badges: ['verified_business'], proof_count: 45, rating_avg: 4.6, rating_count: 45, open_now: true, booking_enabled: true, payment_enabled: false, status: 'active', hours: { mon: ['05:00-23:00'], tue: ['05:00-23:00'], wed: ['05:00-23:00'], thu: ['05:00-23:00'], fri: ['05:00-23:00'], sat: ['06:00-22:00'], sun: ['06:00-22:00'] } },
  { id: 'biz_004', name: 'Pho Saigon 75', category: 'food', description: 'Authentic Vietnamese cuisine in the heart of Dallas.', location_lat: 32.7720, location_lng: -96.7920, trust_score: 82, trust_level: 'trusted', badges: ['verified_business', 'top_rated'], proof_count: 71, rating_avg: 4.8, rating_count: 71, open_now: true, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['11:00-22:00'], tue: ['11:00-22:00'], wed: ['11:00-22:00'], thu: ['11:00-22:00'], fri: ['11:00-23:00'], sat: ['11:00-23:00'], sun: ['11:00-21:00'] } },
  { id: 'biz_005', name: 'Dallas Dental Arts', category: 'dental', description: 'Family dentistry with latest technology.', location_lat: 32.7890, location_lng: -96.7950, trust_score: 90, trust_level: 'highly_trusted', badges: ['verified_business', 'trusted_seller'], proof_count: 120, rating_avg: 4.8, rating_count: 120, open_now: true, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['08:00-17:00'], tue: ['08:00-17:00'], wed: ['08:00-17:00'], thu: ['08:00-17:00'], fri: ['08:00-15:00'], sat: [], sun: [] } },
  { id: 'biz_006', name: 'Uptown Yoga', category: 'fitness', description: 'Hot yoga, vinyasa, and meditation classes.', location_lat: 32.7950, location_lng: -96.8020, trust_score: 75, trust_level: 'trusted', badges: ['verified_business'], proof_count: 38, rating_avg: 4.5, rating_count: 38, open_now: true, booking_enabled: true, payment_enabled: false, status: 'active', hours: { mon: ['06:00-21:00'], tue: ['06:00-21:00'], wed: ['06:00-21:00'], thu: ['06:00-21:00'], fri: ['06:00-20:00'], sat: ['07:00-18:00'], sun: ['08:00-16:00'] } },
  { id: 'biz_007', name: 'The Rustic Table', category: 'food', description: 'Farm-to-table Southern cuisine.', location_lat: 32.7750, location_lng: -96.8030, trust_score: 80, trust_level: 'trusted', badges: ['verified_business'], proof_count: 55, rating_avg: 4.6, rating_count: 55, open_now: true, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['11:00-22:00'], tue: ['11:00-22:00'], wed: ['11:00-22:00'], thu: ['11:00-22:00'], fri: ['11:00-23:00'], sat: ['10:00-23:00'], sun: ['10:00-21:00'] } },
  { id: 'biz_008', name: 'LuxeBrow Studio', category: 'beauty', description: 'Microblading and brow lamination experts.', location_lat: 32.7830, location_lng: -96.7900, trust_score: 88, trust_level: 'highly_trusted', badges: ['verified_business', 'top_rated'], proof_count: 67, rating_avg: 4.9, rating_count: 67, open_now: false, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['10:00-18:00'], tue: ['10:00-18:00'], wed: ['10:00-18:00'], thu: ['10:00-18:00'], fri: ['10:00-18:00'], sat: ['10:00-16:00'], sun: [] } },
  { id: 'biz_009', name: 'Bishop Arts Barbershop', category: 'beauty', description: 'Classic cuts and modern styles.', location_lat: 32.7490, location_lng: -96.8260, trust_score: 72, trust_level: 'trusted', badges: ['verified_business'], proof_count: 33, rating_avg: 4.5, rating_count: 33, open_now: true, booking_enabled: true, payment_enabled: false, status: 'active', hours: { mon: ['09:00-19:00'], tue: ['09:00-19:00'], wed: ['09:00-19:00'], thu: ['09:00-19:00'], fri: ['09:00-19:00'], sat: ['08:00-17:00'], sun: [] } },
  { id: 'biz_010', name: 'Cowork DFW', category: 'coworking', description: 'Flexible workspace for founders and remote teams.', location_lat: 32.7870, location_lng: -96.7980, trust_score: 68, trust_level: 'trusted', badges: ['verified_business'], proof_count: 20, rating_avg: 4.3, rating_count: 20, open_now: true, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['07:00-22:00'], tue: ['07:00-22:00'], wed: ['07:00-22:00'], thu: ['07:00-22:00'], fri: ['07:00-22:00'], sat: ['08:00-18:00'], sun: ['08:00-18:00'] } },
  { id: 'biz_011', name: 'Tacos El Primo', category: 'food', description: 'Street-style tacos and fresh salsas.', location_lat: 32.7690, location_lng: -96.8100, trust_score: 76, trust_level: 'trusted', badges: ['top_rated'], proof_count: 48, rating_avg: 4.7, rating_count: 48, open_now: true, booking_enabled: false, payment_enabled: false, status: 'active', hours: { mon: ['10:00-22:00'], tue: ['10:00-22:00'], wed: ['10:00-22:00'], thu: ['10:00-22:00'], fri: ['10:00-24:00'], sat: ['10:00-24:00'], sun: ['10:00-20:00'] } },
  { id: 'biz_012', name: 'Zen Spa Dallas', category: 'beauty', description: 'Full-service spa with massage and facials.', location_lat: 32.7920, location_lng: -96.7860, trust_score: 85, trust_level: 'highly_trusted', badges: ['verified_business', 'trusted_seller'], proof_count: 72, rating_avg: 4.8, rating_count: 72, open_now: true, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['09:00-20:00'], tue: ['09:00-20:00'], wed: ['09:00-20:00'], thu: ['09:00-20:00'], fri: ['09:00-21:00'], sat: ['09:00-21:00'], sun: ['10:00-18:00'] } },
  { id: 'biz_013', name: 'Code & Beans', category: 'food', description: 'Coffee shop for developers. WiFi, power, community.', location_lat: 32.7855, location_lng: -96.7945, trust_score: 70, trust_level: 'trusted', badges: [], proof_count: 25, rating_avg: 4.4, rating_count: 25, open_now: true, booking_enabled: false, payment_enabled: true, status: 'active', hours: { mon: ['07:00-22:00'], tue: ['07:00-22:00'], wed: ['07:00-22:00'], thu: ['07:00-22:00'], fri: ['07:00-22:00'], sat: ['08:00-20:00'], sun: ['08:00-18:00'] } },
  { id: 'biz_014', name: 'CrossFit Deep Ellum', category: 'fitness', description: 'Functional fitness for all levels.', location_lat: 32.7840, location_lng: -96.7820, trust_score: 74, trust_level: 'trusted', badges: ['verified_business'], proof_count: 30, rating_avg: 4.5, rating_count: 30, open_now: true, booking_enabled: true, payment_enabled: false, status: 'active', hours: { mon: ['05:30-21:00'], tue: ['05:30-21:00'], wed: ['05:30-21:00'], thu: ['05:30-21:00'], fri: ['05:30-20:00'], sat: ['07:00-14:00'], sun: ['08:00-12:00'] } },
  { id: 'biz_015', name: 'Bright Smile Orthodontics', category: 'dental', description: 'Invisalign and braces specialists.', location_lat: 32.7780, location_lng: -96.8050, trust_score: 86, trust_level: 'highly_trusted', badges: ['verified_business'], proof_count: 58, rating_avg: 4.7, rating_count: 58, open_now: true, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['08:00-17:00'], tue: ['08:00-17:00'], wed: ['08:00-17:00'], thu: ['08:00-17:00'], fri: ['08:00-14:00'], sat: [], sun: [] } },
  { id: 'biz_016', name: 'The Grind House', category: 'food', description: 'Specialty burgers and craft beer.', location_lat: 32.7700, location_lng: -96.7980, trust_score: 65, trust_level: 'trusted', badges: [], proof_count: 18, rating_avg: 4.2, rating_count: 18, open_now: true, booking_enabled: false, payment_enabled: true, status: 'active', hours: { mon: ['11:00-23:00'], tue: ['11:00-23:00'], wed: ['11:00-23:00'], thu: ['11:00-23:00'], fri: ['11:00-01:00'], sat: ['11:00-01:00'], sun: ['11:00-22:00'] } },
  { id: 'biz_017', name: 'Lash & Co.', category: 'beauty', description: 'Eyelash extensions and lift.', location_lat: 32.7910, location_lng: -96.7990, trust_score: 79, trust_level: 'trusted', badges: ['verified_business'], proof_count: 41, rating_avg: 4.6, rating_count: 41, open_now: false, booking_enabled: true, payment_enabled: true, status: 'active', hours: { mon: ['10:00-19:00'], tue: ['10:00-19:00'], wed: ['10:00-19:00'], thu: ['10:00-19:00'], fri: ['10:00-19:00'], sat: ['10:00-16:00'], sun: [] } },
  { id: 'biz_018', name: 'Dallas Print Lab', category: 'services', description: 'Custom prints, signage, and packaging.', location_lat: 32.7730, location_lng: -96.8090, trust_score: 60, trust_level: 'trusted', badges: [], proof_count: 12, rating_avg: 4.1, rating_count: 12, open_now: true, booking_enabled: false, payment_enabled: false, status: 'active', hours: { mon: ['09:00-17:00'], tue: ['09:00-17:00'], wed: ['09:00-17:00'], thu: ['09:00-17:00'], fri: ['09:00-17:00'], sat: [], sun: [] } },
  { id: 'biz_019', name: 'Pulse Pilates', category: 'fitness', description: 'Reformer Pilates studio.', location_lat: 32.7960, location_lng: -96.7910, trust_score: 71, trust_level: 'trusted', badges: ['verified_business'], proof_count: 28, rating_avg: 4.5, rating_count: 28, open_now: true, booking_enabled: true, payment_enabled: false, status: 'active', hours: { mon: ['06:00-20:00'], tue: ['06:00-20:00'], wed: ['06:00-20:00'], thu: ['06:00-20:00'], fri: ['06:00-19:00'], sat: ['07:00-15:00'], sun: ['08:00-13:00'] } },
  { id: 'biz_020', name: 'Boba House DFW', category: 'food', description: 'Fresh boba tea and Asian desserts.', location_lat: 32.7815, location_lng: -96.7870, trust_score: 66, trust_level: 'trusted', badges: [], proof_count: 22, rating_avg: 4.4, rating_count: 22, open_now: true, booking_enabled: false, payment_enabled: true, status: 'active', hours: { mon: ['11:00-21:00'], tue: ['11:00-21:00'], wed: ['11:00-21:00'], thu: ['11:00-21:00'], fri: ['11:00-22:00'], sat: ['11:00-22:00'], sun: ['12:00-20:00'] } },
];

// ─── Signals (10 offers + presence) ───────────────────────────────────────

export const SEED_SIGNALS = [
  { _id: 'signal_001', owner_type: 'business', owner_id: 'biz_001', type: 'offer', title: '20% off Manicure today', category: 'beauty', location: { type: 'Point', coordinates: [-96.7970, 32.7767] }, radius: 300, visibility: 'public', verified: true, trust_score_snapshot: 94, status: 'active', metadata: { discount_percent: 20, booking_enabled: true } },
  { _id: 'signal_002', owner_type: 'business', owner_id: 'biz_002', type: 'offer', title: 'Buy 1 Get 1 Free Latte', category: 'food', location: { type: 'Point', coordinates: [-96.7838, 32.7835] }, radius: 200, visibility: 'public', verified: true, trust_score_snapshot: 87, status: 'active', metadata: { discount: 'BOGO' } },
  { _id: 'signal_003', owner_type: 'business', owner_id: 'biz_003', type: 'offer', title: 'Free first personal training session', category: 'fitness', location: { type: 'Point', coordinates: [-96.8005, 32.7801] }, radius: 500, visibility: 'public', verified: true, trust_score_snapshot: 78, status: 'active', metadata: { discount: 'Free trial' } },
  { _id: 'signal_004', owner_type: 'business', owner_id: 'biz_005', type: 'offer', title: 'New Patient Special — $99 Cleaning + X-ray', category: 'dental', location: { type: 'Point', coordinates: [-96.7950, 32.7890] }, radius: 1000, visibility: 'public', verified: true, trust_score_snapshot: 90, status: 'active', metadata: { discount: '$99 special' } },
  { _id: 'signal_005', owner_type: 'business', owner_id: 'biz_008', type: 'offer', title: '$50 off Microblading this week', category: 'beauty', location: { type: 'Point', coordinates: [-96.7900, 32.7830] }, radius: 400, visibility: 'public', verified: true, trust_score_snapshot: 88, status: 'active', metadata: { discount: '$50 off' } },
  { _id: 'signal_006', owner_type: 'business', owner_id: 'biz_012', type: 'offer', title: '30% off Swedish Massage', category: 'beauty', location: { type: 'Point', coordinates: [-96.7860, 32.7920] }, radius: 500, visibility: 'public', verified: true, trust_score_snapshot: 85, status: 'active', metadata: { discount_percent: 30 } },
  { _id: 'signal_007', owner_type: 'business', owner_id: 'biz_004', type: 'offer', title: 'Free spring rolls with pho order', category: 'food', location: { type: 'Point', coordinates: [-96.7920, 32.7720] }, radius: 300, visibility: 'public', verified: true, trust_score_snapshot: 82, status: 'active', metadata: { discount: 'Free item' } },
  { _id: 'signal_008', owner_type: 'business', owner_id: 'biz_010', type: 'offer', title: 'First week free — Day Pass', category: 'coworking', location: { type: 'Point', coordinates: [-96.7980, 32.7870] }, radius: 800, visibility: 'public', verified: true, trust_score_snapshot: 68, status: 'active', metadata: { discount: 'Free week' } },
  { _id: 'signal_009', owner_type: 'business', owner_id: 'biz_015', type: 'offer', title: 'Free Invisalign Consultation', category: 'dental', location: { type: 'Point', coordinates: [-96.8050, 32.7780] }, radius: 1500, visibility: 'public', verified: true, trust_score_snapshot: 86, status: 'active', metadata: { discount: 'Free consult' } },
  { _id: 'signal_010', owner_type: 'business', owner_id: 'biz_007', type: 'offer', title: 'Happy Hour — $5 appetizers', category: 'food', location: { type: 'Point', coordinates: [-96.8030, 32.7750] }, radius: 400, visibility: 'public', verified: true, trust_score_snapshot: 80, status: 'active', metadata: { discount: '$5 apps' } },
  // Presence signals
  { _id: 'signal_011', owner_type: 'user', owner_id: 'user_demo_1', type: 'presence', title: 'Working from Deep Ellum Coffee', category: 'general', location: { type: 'Point', coordinates: [-96.7838, 32.7835] }, radius: 100, visibility: 'public', verified: false, trust_score_snapshot: 45, status: 'active', metadata: {} },
  { _id: 'signal_012', owner_type: 'user', owner_id: 'user_demo_2', type: 'presence', title: 'At Iron Temple — leg day', category: 'fitness', location: { type: 'Point', coordinates: [-96.8005, 32.7801] }, radius: 100, visibility: 'public', verified: false, trust_score_snapshot: 52, status: 'active', metadata: {} },
  { _id: 'signal_013', owner_type: 'user', owner_id: 'user_demo_3', type: 'intent', title: 'Looking for a dentist that takes walk-ins', category: 'dental', location: { type: 'Point', coordinates: [-96.7960, 32.7800] }, radius: 2000, visibility: 'public', verified: false, trust_score_snapshot: 38, status: 'active', metadata: {} },
];

// ─── Circles (5) ──────────────────────────────────────────────────────────

export const SEED_CIRCLES = [
  { id: 'circle_001', name: 'Dallas AI Builders', slug: 'dallas-ai-builders', category: 'AI', city: 'Dallas', description: 'Building the future with AI in DFW.', owner_id: 'user_system', visibility: 'public', verification_level: 1, trust_score: 80, trust_level: 'trusted', badges: ['active_community'], member_count: 532, event_count: 18, status: 'active' },
  { id: 'circle_002', name: 'DFW Startup Network', slug: 'dfw-startup-network', category: 'Business', city: 'Dallas', description: 'Founders, investors, and builders connecting.', owner_id: 'user_system', visibility: 'public', verification_level: 1, trust_score: 75, trust_level: 'trusted', badges: ['active_community'], member_count: 310, event_count: 12, status: 'active' },
  { id: 'circle_003', name: 'Dallas Foodies', slug: 'dallas-foodies', category: 'Food', city: 'Dallas', description: 'Exploring the best eats in DFW.', owner_id: 'user_system', visibility: 'public', verification_level: 1, trust_score: 72, trust_level: 'trusted', badges: ['active_community'], member_count: 184, event_count: 8, status: 'active' },
  { id: 'circle_004', name: 'DFW Fitness Crew', slug: 'dfw-fitness-crew', category: 'Fitness', city: 'Dallas', description: 'Group workouts, challenges, accountability.', owner_id: 'user_system', visibility: 'public', verification_level: 0, trust_score: 55, trust_level: 'verified', badges: [], member_count: 97, event_count: 5, status: 'active' },
  { id: 'circle_005', name: 'Crypto Dallas', slug: 'crypto-dallas', category: 'Crypto', city: 'Dallas', description: 'Web3, DeFi, and blockchain community.', owner_id: 'user_system', visibility: 'public', verification_level: 1, trust_score: 70, trust_level: 'trusted', badges: ['active_community'], member_count: 128, event_count: 10, status: 'active' },
];

// ─── Events (3) ───────────────────────────────────────────────────────────

export const SEED_EVENTS = [
  { id: 'event_001', title: 'AI Meetup Dallas — March Edition', description: 'Monthly AI builders meetup. Demos, talks, networking.', host_type: 'circle', host_id: 'circle_001', location_name: 'Cowork DFW', location_lat: 32.7870, location_lng: -96.7980, start_time: new Date(Date.now() + 2 * 3600 * 1000).toISOString(), end_time: new Date(Date.now() + 5 * 3600 * 1000).toISOString(), capacity: 50, joined_count: 32, checkin_count: 0, visibility: 'public', verified: true, status: 'scheduled' },
  { id: 'event_002', title: 'Deep Ellum Food Crawl', description: 'Walk and taste through the best of Deep Ellum.', host_type: 'circle', host_id: 'circle_003', location_name: 'Deep Ellum', location_lat: 32.7835, location_lng: -96.7838, start_time: new Date(Date.now() + 24 * 3600 * 1000).toISOString(), end_time: new Date(Date.now() + 27 * 3600 * 1000).toISOString(), capacity: 30, joined_count: 18, checkin_count: 0, visibility: 'public', verified: true, status: 'scheduled' },
  { id: 'event_003', title: 'Saturday Morning Run Club', description: '5K run starting from Katy Trail.', host_type: 'circle', host_id: 'circle_004', location_name: 'Katy Trail', location_lat: 32.8050, location_lng: -96.8010, start_time: new Date(Date.now() + 48 * 3600 * 1000).toISOString(), end_time: new Date(Date.now() + 49 * 3600 * 1000).toISOString(), capacity: 100, joined_count: 45, checkin_count: 0, visibility: 'public', verified: false, status: 'scheduled' },
];

// ─── Users (10) — Demo profiles across Dallas ─────────────────────────────

export const SEED_USERS = [
  { id: 'user_demo_1', username: 'alex_dallas', display_name: 'Alex Dallas', email: 'alex@example.com', avatar_url: '', bio: 'Founder & builder in Deep Ellum.', city: 'Dallas', location_lat: 32.7835, location_lng: -96.7838, trust_score: 78, trust_level: 'trusted', badges: '["verified"]', role: 'user', status: 'active' },
  { id: 'user_demo_2', username: 'sam_dfw', display_name: 'Sam DFW', email: 'sam@example.com', avatar_url: '', bio: 'UX designer & coffee explorer.', city: 'Dallas', location_lat: 32.7801, location_lng: -96.8005, trust_score: 65, trust_level: 'verified', badges: '["verified"]', role: 'user', status: 'active' },
  { id: 'user_demo_3', username: 'jordan_tx', display_name: 'Jordan TX', email: 'jordan@example.com', avatar_url: '', bio: 'Crypto & DeFi builder.', city: 'Dallas', location_lat: 32.7770, location_lng: -96.7960, trust_score: 82, trust_level: 'trusted', badges: '["verified","active_community"]', role: 'user', status: 'active' },
  { id: 'user_demo_4', username: 'maya_uptown', display_name: 'Maya Uptown', email: 'maya@example.com', avatar_url: '', bio: 'Yoga instructor & wellness coach.', city: 'Dallas', location_lat: 32.7950, location_lng: -96.8020, trust_score: 72, trust_level: 'trusted', badges: '["verified"]', role: 'user', status: 'active' },
  { id: 'user_demo_5', username: 'chris_oak', display_name: 'Chris Oak', email: 'chris@example.com', avatar_url: '', bio: 'Photographer — events & portraits.', city: 'Dallas', location_lat: 32.7490, location_lng: -96.8260, trust_score: 58, trust_level: 'verified', badges: '[]', role: 'user', status: 'active' },
  { id: 'user_demo_6', username: 'priya_dev', display_name: 'Priya Dev', email: 'priya@example.com', avatar_url: '', bio: 'Full-stack engineer. Building in public.', city: 'Dallas', location_lat: 32.7867, location_lng: -96.7983, trust_score: 88, trust_level: 'highly_trusted', badges: '["verified","active_community"]', role: 'user', status: 'active' },
  { id: 'user_demo_7', username: 'lena_fit', display_name: 'Lena Fit', email: 'lena@example.com', avatar_url: '', bio: 'Personal trainer & nutrition coach.', city: 'Dallas', location_lat: 32.7720, location_lng: -96.7920, trust_score: 70, trust_level: 'trusted', badges: '["verified"]', role: 'user', status: 'active' },
  { id: 'user_demo_8', username: 'omar_biz', display_name: 'Omar Biz', email: 'omar@example.com', avatar_url: '', bio: 'Small business owner. Local first.', city: 'Dallas', location_lat: 32.7820, location_lng: -96.7900, trust_score: 60, trust_level: 'verified', badges: '[]', role: 'user', status: 'active' },
  { id: 'user_demo_9', username: 'nina_arts', display_name: 'Nina Arts', email: 'nina@example.com', avatar_url: '', bio: 'Artist & muralist in Bishop Arts.', city: 'Dallas', location_lat: 32.7480, location_lng: -96.8270, trust_score: 55, trust_level: 'verified', badges: '["verified"]', role: 'user', status: 'active' },
  { id: 'user_demo_10', username: 'kai_tech', display_name: 'Kai Tech', email: 'kai@example.com', avatar_url: '', bio: 'AI researcher and open-source contributor.', city: 'Dallas', location_lat: 32.7910, location_lng: -96.7970, trust_score: 91, trust_level: 'highly_trusted', badges: '["verified","active_community"]', role: 'user', status: 'active' },
];

// ─── Agents (3) ───────────────────────────────────────────────────────────

export const SEED_AGENTS = [
  { _id: 'agent_001', name: 'Ask Gao', type: 'system', owner_type: 'gao', owner_id: 'gao_system', verified: true, trust_score: 98, trust_level: 'highly_trusted', capabilities: ['answer_questions', 'find_nearby', 'recommend_options', 'trust_lookup', 'check_availability'], permission_scope: { can_suggest: true, can_prepare_action: true, execute_with_approval: ['create_booking'], auto_execute: [], requires_user_approval: true, can_access_payment: false }, location: { type: 'Point', coordinates: [-96.7970, 32.7767] }, map_visible: true, status: 'active' },
  { _id: 'agent_002', name: 'Glow Nails Concierge', type: 'merchant', owner_type: 'business', owner_id: 'biz_001', verified: true, trust_score: 94, trust_level: 'highly_trusted', capabilities: ['check_availability', 'create_booking', 'send_reminders', 'answer_questions'], permission_scope: { can_suggest: true, can_prepare_action: true, execute_with_approval: ['create_booking', 'send_reminders'], auto_execute: [], requires_user_approval: true, can_access_payment: false }, location: { type: 'Point', coordinates: [-96.7970, 32.7770] }, map_visible: true, status: 'active' },
  { _id: 'agent_003', name: 'Dallas Dental Assistant', type: 'merchant', owner_type: 'business', owner_id: 'biz_005', verified: true, trust_score: 90, trust_level: 'highly_trusted', capabilities: ['check_availability', 'create_booking', 'answer_questions'], permission_scope: { can_suggest: true, can_prepare_action: true, execute_with_approval: ['create_booking'], auto_execute: [], requires_user_approval: true, can_access_payment: false }, location: { type: 'Point', coordinates: [-96.7950, 32.7895] }, map_visible: true, status: 'active' },
];
