name = "gao-social-dev"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "gao-social-dev"
database_id = "65f8c45c-b3d4-4f02-91b1-e6f828cc2e26"

[[kv_namespaces]]
binding = "SOCIAL_KV"
id = "49968b6c630147a284b3b2e93eec6422"

[vars]
NEXT_PUBLIC_APP_URL = "https://app-dev.gao.social"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "784048251848-r76tcdq5eevmt440tv0f8il0qsaatnin.apps.googleusercontent.com"
