/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/api/v1/app-settings/active-version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get active app version
     * @description Get active app version information for a specific app type and platform
     */
    get: {
      parameters: {
        query: {
          /** @description Platform (ios, android, web) */
          platform: string;
        };
        header: {
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['service.GetActiveAppVersionResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/app-settings/platform': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get app settings by platform
     * @description Get all app settings for a specific app type and platform
     */
    get: {
      parameters: {
        query: {
          /** @description Platform (ios, android, web) */
          platform: string;
        };
        header: {
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['service.GetActiveAppVersionResponse'][];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/2fa/disable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Disable 2FA
     * @description Disables 2FA for a user after verifying the code
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description 2FA disable request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.TwoFactorDisableRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/2fa/enable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enable 2FA
     * @description Enables 2FA for a user after verifying the code
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description 2FA enable request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.TwoFactorEnableRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/2fa/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Setup 2FA
     * @description Initiates the 2FA setup process and returns QR code
     */
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.TwoFactorSetupResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/2fa/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get 2FA status
     * @description Gets the 2FA status of a user
     */
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.TwoFactorStatusResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/2fa/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify 2FA code
     * @description Verifies a 2FA code from Google Authenticator
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description 2FA verification request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.TwoFactorVerifyRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.TwoFactorVerifyResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/authorized': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verify token
     * @description Verify token signature, expiry, and cache
     */
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description Bearer Token */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/complete-registration': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Complete user registration
     * @description Complete user registration with username and password
     */
    put: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID': string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
          /** @description Temporary token */
          'Tmp-Token': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Registration completion request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.CompleteRegistrationRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.AuthResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/extend-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Extend token
     * @description Extend access token with new expiry time. If token has no exp claim, only updates expiry in cache/database. Otherwise generates new token.
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Bearer Token */
          Authorization: string;
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Extend token request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.ExtendTokenRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.AuthResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/fcm-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Update FCM token for push notifications
     * @description Update FCM token for the authenticated user to receive push notifications
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description FCM token details */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.UpdateFCMTokenRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate user
     * @description Authenticate user with phone number/email and password
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Login credentials */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.LoginRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.AuthResponse'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login-wallet': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login with wallet
     * @description Login using wallet signature
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Login request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.LoginWalletRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.LoginWalletResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/passkey/nonce': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get nonce message for passkey registration/login
     * @description Get a nonce message for passkey and user info if device already has a registered user
     */
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID': string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin, payii-o2o) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.PasskeyNonceResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/passkey/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register new passkey (without wallet)
     * @description Register new passkey for payii-o2o app without wallet requirement
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (must be payii-o2o) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Register new passkey request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.RegisterNewPasskeyRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.RegisterNewPasskeyResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/profile-by-wallet': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user profile by wallet address
     * @description Get user profile (userId, username, displayName, avatar_url) by wallet address
     */
    get: {
      parameters: {
        query: {
          /** @description Wallet Address */
          wallet_address: string;
        };
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (gao-social, gao-travel, runx, toii-ai-depin, meshii) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.UserProfileByWallet'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/profiles-by-passkey/{passkey_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user profiles by passkey ID
     * @description Get list of user profiles (username and avatar) mapped to a passkey ID
     */
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path: {
          /** @description Passkey ID */
          passkey_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.GetUserProfilesByPasskeyResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/profiles-by-wallet': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get user profiles by wallet addresses
     * @description Get user profiles (userId, username, displayName, avatar_url) for multiple wallet addresses
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (gao-social, gao-travel, runx, toii-ai-depin, meshii) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description List of wallet addresses */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.GetUserProfilesByWalletAddressesRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.GetUserProfilesByWalletAddressesResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh access token
     * @description Get new access token using refresh token
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
          /** @description Refresh token */
          'Refresh-Token': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.AuthResponse'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/request-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request OTP with phone number or email
     * @description Request OTP with phone number or email
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description User request OTP with phone number or email */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.RequestWithOTP'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset password using temporary token
     * @description Reset password using temporary token received after OTP verification
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
          /** @description Temporary token */
          'Tmp-Token': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Reset password details */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.ResetPasswordRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user sessions
     * @description Get current user's sessions
     */
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.UserSessionResponse'][];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout user
     * @description Logout user and invalidate refresh token
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
          /** @description Refresh token */
          'Refresh-Token': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/logout-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout all user sessions
     * @description Logout all user sessions and invalidate all access tokens
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/logout-session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout user session
     * @description Logout user session and invalidate access token
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Logout session details */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.LogoutSessionRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/social/{type}/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Social OAuth callback
     * @description Handles social OAuth callback and creates/updates user
     */
    post: {
      parameters: {
        query: {
          /** @description Authorization code */
          code: string;
        };
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path: {
          /** @description Social provider type (google/apple/discord) */
          type: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.AuthResponse'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/social/{type}/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Social OAuth login
     * @description Redirects to social OAuth login page
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path: {
          /** @description Social provider type (google/apple/discord) */
          type: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.SocialAuthResponse'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/social/{type}/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Social OAuth tokens verification
     * @description Verifies social OAuth tokens and creates/updates user
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path: {
          /** @description Social provider type (google/apple/discord) */
          type: string;
        };
        cookie?: never;
      };
      /** @description Social OAuth tokens */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.SocialTokensRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.AuthResponse'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/users/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change password
     * @description Change password
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Change password details */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.ChangePasswordRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['response.ResultResponse'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/verify-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify OTP with phone number or email
     * @description Verify OTP sent to user's phone number or email and complete registration, forgot password, change phone number, change email
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description OTP verification details */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.VerifyOTPRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.VerifyOTPResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/wallet': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login or register wallet
     * @description Login or register wallet
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Login or register request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.LoginOrRegisterWalletRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.LoginWalletResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/wallet-nonce': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get nonce message for wallet signature
     * @description Get a nonce message that needs to be signed by the wallet, with userId and username available
     */
    get: {
      parameters: {
        query: {
          /** @description Wallet address */
          address: string;
        };
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.WalletNonceResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/wallet/detail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get wallet by address
     * @description Get wallet details by wallet address for authenticated user
     */
    get: {
      parameters: {
        query: {
          /** @description Wallet address */
          wallet_address: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.WalletDetailResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/wallet/login-passkey': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login with passkey
     * @description Login using passkey authentication
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type (toii-social, gao-travel, runx, toii-ai-depin) */
          'App-Type': string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Login passkey request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.LoginPasskeyRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.LoginPasskeyResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/wallet/passkey/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register passkey
     * @description Register passkey for wallet authentication
     */
    post: {
      parameters: {
        query?: never;
        header: {
          /** @description Device ID */
          'Device-ID'?: string;
          /** @description App Type */
          'App-Type': string;
          /** @description Authorization */
          Authorization: string;
        };
        path?: never;
        cookie?: never;
      };
      /** @description Register passkey request */
      requestBody: {
        content: {
          'application/json': components['schemas']['models.RegisterPasskeyRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.RegisterPasskeyResponse'];
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              error?: components['schemas']['response.ErrorDetail'];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/crypto/quotes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get cryptocurrency quotes
     * @description Forward request to CoinMarketCap API to get cryptocurrency quotes
     */
    get: {
      parameters: {
        query?: {
          /** @description Cryptocurrency symbols (comma-separated) */
          symbol?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/users/{user_id}/wallet': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user wallet address
     * @description Get user wallet address (internal service endpoint)
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description User ID */
          user_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'] & {
              data?: components['schemas']['models.UserWalletResponse'];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['response.CommonResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    'errors.ValidationError': {
      field?: string;
      message?: string;
    };
    /**
     * @description App type (gao-social, gao-travel, runx, toii-ai-depin)
     * @enum {string}
     */
    'models.AppType':
      | 'payii-o2o'
      | 'gao-social'
      | 'toii-social'
      | 'gao-travel'
      | 'runx'
      | 'toii-ai-depin'
      | 'meshii'
      | 'crm';
    'models.AppVersion': {
      /** @description @Description Build number */
      build?: string;
      /** @description @Description Major version number */
      major?: number;
      /** @description @Description Maximum supported OS version */
      max_os_version?: string;
      /** @description @Description Minimum supported OS version */
      min_os_version?: string;
      /** @description @Description Minor version number */
      minor?: number;
      /** @description @Description Patch version number */
      patch?: number;
      /** @description @Description Platform (ios, android, web) */
      platform?: string;
      /** @description @Description Version string (e.g., "1.0.0") */
      version?: string;
    };
    'models.AssertionResponse': {
      id?: string;
      rawId?: string;
      response?: {
        authenticatorData?: string;
        clientDataJSON?: string;
        signature?: string;
        userHandle?: string;
      };
      type?: string;
    };
    'models.AuthResponse': {
      /** @description @Description Access token of the user */
      access_token?: string;
      /** @description @Description Expired time of the access token */
      expired_at?: string;
      /** @description @Description is new user or not */
      is_new_user?: boolean;
      /** @description @Description Refresh token of the user */
      refresh_token?: string;
      /** @description @Description Require 2FA */
      require_2fa?: boolean;
      /** @description @Description Temporary token of the user */
      tmp_token?: string;
    };
    'models.ChangePasswordRequest': {
      /** @description @Description New password of the user */
      new_password: string;
      /** @description @Description Old password of the user */
      old_password: string;
    };
    'models.CompleteRegistrationRequest': {
      /**
       * @description @Description App type (toii-social, gao-travel, runx, toii-ai-depin, meshii, gao-social, crm)
       * @enum {string}
       */
      appType?:
        | 'toii-social'
        | 'gao-travel'
        | 'runx'
        | 'toii-ai-depin'
        | 'meshii'
        | 'gao-social'
        | 'crm';
      /** @description @Description Email of the user (required if phone number is not provided) */
      email?: string;
      /** @description @Description Network name of the user (ethereum, solana) */
      networkBase?: components['schemas']['models.NetworkBase'];
      /** @description @Description Password to set */
      password?: string;
      /** @description @Description Phone number of the user (required if email is not provided) */
      phoneNumber?: string;
      /** @description @Description Type of registration (phone, email, wallet, social) */
      registerType: components['schemas']['models.RegisterType'];
      /** @description @Description Salt */
      salt?: string;
      /** @description @Description UserID (optional, will be auto-generated if not provided) */
      userId?: string;
      /** @description @Description Username to set */
      username: string;
      /** @description @Description Wallet address of the user */
      walletAddress?: string;
      /** @description @Description Type of wallet (metamask, walletconnect, coinbase, trust, binance, bitkeep, tokenpocket, imtoken, bitpie, mykey) */
      walletProvider?: components['schemas']['models.WalletProvider'];
    };
    'models.ExtendTokenRequest': {
      /** @description @Description Expiry time in minutes for the new token */
      expiry_after_minutes: number;
    };
    'models.GetUserProfilesByPasskeyResponse': {
      /** @description @Description List of user profiles */
      profiles?: components['schemas']['models.UserProfile'][];
    };
    'models.GetUserProfilesByWalletAddressesRequest': {
      /** @description @Description List of wallet addresses to query */
      wallet_addresses: string[];
    };
    'models.GetUserProfilesByWalletAddressesResponse': {
      /** @description @Description Map of wallet address to user profile (key: wallet_address, value: profile) */
      profiles?: {
        [key: string]: components['schemas']['models.UserProfileByWallet'];
      };
    };
    'models.JSONBMap': {
      [key: string]: unknown;
    };
    'models.LoginOrRegisterWalletRequest': {
      /** @description @Description Wallet address */
      address: string;
      /** @description @Description APNS token for push notifications */
      apnsToken?: string;
      /** @description @Description FCM token for push notifications */
      fcmToken?: string;
      /** @description @Description Network base */
      networkBase: components['schemas']['models.NetworkBase'];
      /** @description @Description Platform (ios, android, web) */
      platform?: string;
      /** @description @Description Signature for wallet verification */
      signature: string;
      /** @description @Description UserID (optional, will be auto-generated if not provided) */
      userId?: string;
      /** @description @Description Username (optional, will be auto-generated if not provided) */
      username?: string;
      /** @description @Description wallet type */
      walletProvider: components['schemas']['models.WalletProvider'];
    };
    'models.LoginPasskeyRequest': {
      /** @description @Description APNS token for push notifications */
      apnsToken?: string;
      /** @description @Description Assertion response from passkey */
      assertionInfo: components['schemas']['models.AssertionResponse'];
      /** @description @Description FCM token for push notifications */
      fcmToken?: string;
      /** @description @Description Platform (ios, android, web) */
      platform?: string;
      /**
       * @description @Description Wallet address
       *     Address string `json:"address" binding:"required"`
       *     @Description Signature for wallet verification
       *     Signature string `json:"signature" binding:"required"`
       *     @Description User ID
       */
      userId: string;
    };
    'models.LoginPasskeyResponse': {
      /** @description @Description Access token of the user */
      access_token?: string;
      /** @description @Description Expired time of the access token */
      expired_at?: string;
      /** @description @Description is new user or not */
      is_new_user?: boolean;
      /** @description @Description Original username used when creating the passkey */
      passkey_username?: string;
      /** @description @Description purpose of the temporary token */
      purpose?: components['schemas']['models.OTPPurpose'];
      /** @description @Description Refresh token of the user */
      refresh_token?: string;
      /** @description @Description Require 2FA */
      require_2fa?: boolean;
      /** @description @Description Temporary token of the user */
      tmp_token?: string;
    };
    'models.LoginRequest': {
      /** @description @Description Email of the user */
      email?: string;
      /** @description @Description Password of the user */
      password: string;
      /** @description @Description Phone number of the user */
      phoneNumber?: string;
    };
    'models.LoginWalletRequest': {
      /** @description @Description Wallet address */
      address: string;
      /** @description @Description Signature for wallet verification */
      signature: string;
      /** @description @Description wallet type */
      walletProvider: components['schemas']['models.WalletProvider'];
    };
    'models.LoginWalletResponse': {
      /** @description @Description Access token of the user */
      access_token?: string;
      /** @description @Description Expired time of the access token */
      expired_at?: string;
      /** @description @Description is new user or not */
      is_new_user?: boolean;
      /** @description @Description purpose of the temporary token */
      purpose?: components['schemas']['models.OTPPurpose'];
      /** @description @Description Refresh token of the user */
      refresh_token?: string;
      /** @description @Description Require 2FA */
      require_2fa?: boolean;
      /** @description @Description Temporary token of the user */
      tmp_token?: string;
    };
    'models.LogoutSessionRequest': {
      /** @description @Description ID of the user's session */
      session_id: string;
    };
    /**
     * @description Network name of the user (ethereum, solana)
     * @enum {string}
     */
    'models.NetworkBase': 'ethereum' | 'solana';
    /**
     * @description OTP purpose (register, forgot_password, change_phone, change_email, login)
     * @enum {string}
     */
    'models.OTPPurpose': 'register' | 'forgot_password' | 'change_phone' | 'change_email' | 'login';
    'models.PasskeyNonceResponse': {
      /** @description @Description Nonce message để ký */
      message?: string;
      /** @description @Description User ID (nếu device đã có user đăng ký) */
      userId?: string;
      /** @description @Description Username (nếu device đã có user đăng ký) */
      username?: string;
    };
    'models.RegisterNewPasskeyRequest': {
      /** @description @Description APNS token for push notifications */
      apnsToken?: string;
      /** @description @Description WebAuthn registration response */
      attestationInfo: components['schemas']['models.WebAuthnRegistrationResponse'];
      /** @description @Description Email address (optional) */
      email?: string;
      /** @description @Description FCM token for push notifications */
      fcmToken?: string;
      /** @description @Description Network base */
      network_base?: components['schemas']['models.NetworkBase'];
      /** @description @Description Phone number (optional) */
      phone_number?: string;
      /** @description @Description Platform (ios, android, web) */
      platform?: string;
      /** @description @Description Salt */
      salt?: string;
      /** @description @Description UserID (optional, will be auto-generated if not provided) */
      user_id?: string;
      /** @description @Description Username (optional, will be auto-generated if not provided) */
      username?: string;
      /** @description @Description Wallet address */
      wallet_address?: string;
      /** @description @Description Wallet provider */
      wallet_provider?: components['schemas']['models.WalletProvider'];
    };
    'models.RegisterNewPasskeyResponse': {
      /** @description @Description Access token of the user */
      access_token?: string;
      /** @description @Description Expired time of the access token */
      expired_at?: string;
      /** @description @Description is new user or not */
      is_new_user?: boolean;
      /** @description @Description Passkey ID */
      passkey_id?: string;
      /** @description @Description Refresh token of the user */
      refresh_token?: string;
      /** @description @Description Require 2FA */
      require_2fa?: boolean;
    };
    'models.RegisterPasskeyRequest': {
      /** @description @Description Wallet address */
      address: string;
      /** @description @Description WebAuthn registration response */
      attestationInfo: components['schemas']['models.WebAuthnRegistrationResponse'];
      /** @description @Description Signature for wallet verification */
      signature?: string;
    };
    'models.RegisterPasskeyResponse': {
      /** @description @Description Passkey ID */
      passkey_id?: string;
    };
    /**
     * @description Register type (phone, email, wallet, google, apple, discord, telegram, x, facebook)
     * @enum {string}
     */
    'models.RegisterType': 'phone' | 'email' | 'wallet' | 'social';
    /** @description Request with OTP (phoneNumber, email, purpose) */
    'models.RequestWithOTP': {
      /** @description @Description Email of the user */
      email?: string;
      /** @description @Description Phone number of the user */
      phoneNumber?: string;
      /** @description @Description OTP purpose (register, forgot_password, change_phone, change_email, login) */
      purpose: components['schemas']['models.OTPPurpose'];
    };
    'models.ResetPasswordRequest': {
      /** @description @Description New password to set */
      new_password: string;
    };
    'models.SocialAuthResponse': {
      /** @description OAuth URL for login */
      url?: string;
    };
    'models.SocialTokensRequest': {
      /** @description Required for Google and Discord */
      access_token?: string;
      /** @description Required for Google and Apple */
      id_token?: string;
    };
    /**
     * @description Token temporary purpose (login, register, forgot_password, change_phone, change_email)
     * @enum {string}
     */
    'models.TokenTmpPurpose':
      | 'login'
      | 'register'
      | 'forgot_password'
      | 'change_phone'
      | 'change_email';
    'models.TwoFactorDisableRequest': {
      /** @description 2FA code from Google Authenticator */
      code: string;
    };
    'models.TwoFactorEnableRequest': {
      /** @description 2FA code from Google Authenticator */
      code: string;
    };
    'models.TwoFactorSetupResponse': {
      /** @description QR code URL for Google Authenticator */
      qr_code_url?: string;
      /** @description Secret key for manual entry */
      secret?: string;
    };
    'models.TwoFactorStatusResponse': {
      /** @description @Description Whether 2FA is enabled */
      enabled?: boolean;
    };
    'models.TwoFactorVerifyRequest': {
      /** @description @Description App type (toii-social, gao-travel, runx, toii-ai-depin) */
      appType: components['schemas']['models.AppType'];
      /** @description 2FA code from Google Authenticator */
      code: string;
      /**
       * @description @Description Purpose of OTP verification. Allowed values: register, forgot_password, change_phone, change_email
       *     @Enum register forgot_password change_phone change_email
       */
      purpose?: components['schemas']['models.TokenTmpPurpose'];
    };
    'models.TwoFactorVerifyResponse': {
      /** @description @Description Access token of the user */
      access_token?: string;
      /** @description @Description Expired time of the access token */
      expired_at?: string;
      /** @description @Description Refresh token of the user */
      refresh_token?: string;
      /** @description @Description success or not */
      success?: boolean;
    };
    'models.UpdateFCMTokenRequest': {
      /** @description @Description FCM token for push notifications */
      fcmToken: string;
      /**
       * @description @Description Platform type (web, ios, android)
       * @enum {string}
       */
      platform: 'web' | 'ios' | 'android';
    };
    'models.UserProfile': {
      /** @description @Description URL to user's avatar image */
      avatar_url?: string;
      /** @description @Description First name of the user */
      first_name?: string;
      /** @description @Description Display name of the user */
      full_name?: string;
      /** @description @Description User ID */
      id?: string;
      /** @description @Description Inbox ID for user messaging */
      inbox_id?: string;
      /** @description @Description Last name of the user */
      last_name?: string;
      /** @description @Description Original username used when creating the passkey */
      passkey_username?: string;
      /** @description @Description Username of the user */
      username?: string;
    };
    'models.UserProfileByWallet': {
      /** @description @Description URL to user's avatar image */
      avatar_url?: string;
      /** @description @Description Display name of the user */
      displayName?: string;
      /** @description @Description Inbox ID for user messaging */
      inbox_id?: string;
      /** @description @Description User ID */
      userId?: string;
      /** @description @Description Username of the user */
      username?: string;
    };
    'models.UserSessionResponse': {
      /** @description @Description Whether the user is active */
      active?: boolean;
      /** @description @Description App type (toii_social, gao_travel, runx, toii_ai_depin) */
      app_type?: components['schemas']['models.AppType'];
      /** @description @Description Browser of the user */
      browser?: string;
      /** @description @Description Browser version of the user */
      browser_ver?: string;
      /** @description @Description Timestamp of user's creation */
      created_at?: string;
      /** @description @Description Device ID of the user */
      device_id?: string;
      /** @description @Description Device name of the user */
      device_name?: string;
      /** @description @Description Expired time of the user session */
      expires_at?: string;
      /** @description @Description ID of the user session */
      id?: string;
      /** @description @Description IP address of the user */
      ip_address?: string;
      /** @description @Description Whether the user is mobile */
      is_mobile?: boolean;
      /** @description @Description OS of the user */
      os?: string;
      /** @description @Description OS version of the user */
      os_version?: string;
      /** @description @Description Platform of the user */
      platform?: string;
      /** @description @Description Timestamp of user's last update */
      updated_at?: string;
      /** @description @Description ID of the user */
      user_id?: string;
    };
    'models.UserWalletResponse': {
      created_at?: string;
      updated_at?: string;
      userId?: string;
      wallet_address?: string;
    };
    'models.VerifyOTPRequest': {
      /** @description @Description Email of the user */
      email?: string;
      /** @description @Description OTP of the user */
      otp: string;
      /** @description @Description Phone number of the user */
      phoneNumber?: string;
      /**
       * @description @Description Purpose of OTP verification. Allowed values: register, forgot_password, change_phone, change_email
       *     @Enum register forgot_password change_phone change_email
       */
      purpose: components['schemas']['models.OTPPurpose'];
    };
    'models.VerifyOTPResponse': {
      /** @description @Description Expired time of the temporary token */
      expired_at?: string;
      /** @description @Description purpose of the OTP verification */
      purpose?: components['schemas']['models.TokenTmpPurpose'];
      /** @description @Description success or not */
      success?: boolean;
      /** @description @Description Temporary token of the user */
      tmp_token?: string;
    };
    'models.WalletDetailResponse': {
      /** @description @Description Created timestamp */
      created_at?: string;
      /** @description @Description Wallet ID */
      id?: string;
      /** @description @Description Last login timestamp */
      last_login_at?: string;
      /** @description @Description Network base (ethereum, solana) */
      network_base?: string;
      /** @description @Description Salt for wallet verification */
      salt?: string;
      /** @description @Description Updated timestamp */
      updated_at?: string;
      /** @description @Description User ID owner of the wallet */
      userId?: string;
      /** @description @Description Wallet address */
      wallet_address?: string;
      /** @description @Description Wallet provider (metamask, walletconnect, etc) */
      wallet_provider?: string;
    };
    'models.WalletNonceResponse': {
      /** @description @Description Nonce message để ký */
      message?: string;
      /** @description @Description User ID (nếu device đã có user đăng ký) */
      userId?: string;
      /** @description @Description Username (nếu device đã có user đăng ký) */
      username?: string;
    };
    /** @enum {string} */
    'models.WalletProvider':
      | 'metamask'
      | 'walletconnect'
      | 'coinbase'
      | 'trust'
      | 'binance'
      | 'bitkeep'
      | 'tokenpocket'
      | 'imtoken'
      | 'bitpie'
      | 'mykey'
      | 'passkey';
    'models.WebAuthnRegistrationResponse': {
      /** @description @Description Passkey ID */
      id: string;
      /** @description @Description Passkey Raw ID */
      rawId: string;
      /** @description @Description Passkey Response */
      response?: {
        /** @description @Description Passkey Attestation Object */
        attestationObject: string;
        /** @description @Description Passkey Client Data JSON */
        clientDataJSON: string;
      };
      /** @description @Description Passkey Type */
      type: string;
    };
    'response.CommonResponse': {
      /** @description can be null */
      data?: Record<string, never>;
      /** @description can be null */
      error?: components['schemas']['response.ErrorDetail'];
      unix_time?: number;
    };
    'response.ErrorDetail': {
      code?: string;
      context?: {
        [key: string]: unknown;
      };
      details?: components['schemas']['errors.ValidationError'][];
      message?: string;
      messages?: {
        [key: string]: string;
      };
      timestamp?: string;
      trace_id?: string;
    };
    'response.ResultResponse': {
      data?: Record<string, never>;
      success: boolean;
    };
    'service.GetActiveAppVersionResponse': {
      config?: components['schemas']['models.JSONBMap'];
      created_at?: string;
      description?: string;
      id?: string;
      is_active?: boolean;
      updated_at?: string;
      version?: components['schemas']['models.AppVersion'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;