-- ============================================================================
-- Migration 025 — Pet voice (AI-generated diary + greeting)
-- ============================================================================
-- Adds three columns to back the Tier-1 "alive pet" feature:
--
--   • pet_diary        — JSON array of up to 10 diary entries, newest last.
--                        Shape: [{ date, line, mood, type }]. Generated by
--                        Claude on each successful tick + on milestones.
--   • pet_greeting     — Latest cached "hi, you opened the app" line shown
--                        above the pet portrait. Refreshed lazily on mount
--                        when stale (>12h) or when mood would change.
--   • pet_greeting_at  — Timestamp of the cached greeting for staleness.
--
-- All three are NULL by default — old streaks just don't show speech.
-- AI calls are best-effort: if ANTHROPIC_API_KEY is missing, the diary
-- stays empty and the UI quietly hides the speech sections.
--
-- Apply on dev:
--   wrangler d1 execute gao-social-dev --local \
--     --file=src/db/migration-025-pet-voice.sql
-- ============================================================================

ALTER TABLE streaks ADD COLUMN pet_diary       TEXT;
ALTER TABLE streaks ADD COLUMN pet_greeting    TEXT;
ALTER TABLE streaks ADD COLUMN pet_greeting_at TEXT;
