-- ============================================================================
-- Gao Social V3 — Fake Vietnamese Users (100 users across Vietnam)
-- Run after seed-local.sql
-- ============================================================================

-- Ho Chi Minh City (40 users) — District 1, 3, 7, Binh Thanh, Thu Duc
INSERT OR IGNORE INTO users (id, username, display_name, email, avatar_url, bio, city, location_lat, location_lng, trust_score, trust_level, badges, role, status, last_seen_at, created_at, updated_at) VALUES
('vn_hcm_01', 'thanh_bui', 'Thanh Bui', 'thanh.bui@example.com', '', 'Mobile dev | Flutter & React Native', 'Ho Chi Minh City', 10.7731, 106.7030, 72, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-3 minutes'), datetime('now', '-40 days'), datetime('now')),
('vn_hcm_02', 'huong_phan', 'Huong Phan', 'huong.phan@example.com', '', 'Marketing Manager @ Shopee VN', 'Ho Chi Minh City', 10.7815, 106.6993, 80, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-1 minutes'), datetime('now', '-55 days'), datetime('now')),
('vn_hcm_03', 'minh_do', 'Minh Do', 'minh.do@example.com', '', 'Barista & Coffee roaster', 'Ho Chi Minh City', 10.7760, 106.7005, 55, 'verified', '[]', 'user', 'active', datetime('now', '-12 minutes'), datetime('now', '-20 days'), datetime('now')),
('vn_hcm_04', 'ngoc_tran', 'Ngoc Tran', 'ngoc.tran@example.com', '', 'Freelance illustrator & comic artist', 'Ho Chi Minh City', 10.7842, 106.6921, 68, 'verified', '["verified"]', 'user', 'active', datetime('now', '-7 minutes'), datetime('now', '-35 days'), datetime('now')),
('vn_hcm_05', 'duy_le', 'Duy Le', 'duy.le@example.com', '', 'Backend engineer @ VNG', 'Ho Chi Minh City', 10.7698, 106.6914, 76, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-2 minutes'), datetime('now', '-60 days'), datetime('now')),
('vn_hcm_06', 'trang_nguyen', 'Trang Nguyen', 'trang.nguyen@example.com', '', 'Product Designer | Figma nerd', 'Ho Chi Minh City', 10.7889, 106.6851, 82, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-5 minutes'), datetime('now', '-80 days'), datetime('now')),
('vn_hcm_07', 'long_vo', 'Long Vo', 'long.vo@example.com', '', 'Real estate investor & mentor', 'Ho Chi Minh City', 10.7652, 106.7048, 60, 'verified', '[]', 'user', 'active', datetime('now', '-20 minutes'), datetime('now', '-25 days'), datetime('now')),
('vn_hcm_08', 'hanh_ly', 'Hanh Ly', 'hanh.ly@example.com', '', 'English teacher | IELTS prep', 'Ho Chi Minh City', 10.7945, 106.7112, 58, 'verified', '["verified"]', 'user', 'active', datetime('now', '-15 minutes'), datetime('now', '-45 days'), datetime('now')),
('vn_hcm_09', 'khanh_pham', 'Khanh Pham', 'khanh.pham@example.com', '', 'DevOps & Cloud | AWS certified', 'Ho Chi Minh City', 10.7780, 106.6870, 74, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-4 minutes'), datetime('now', '-50 days'), datetime('now')),
('vn_hcm_10', 'thao_hoang', 'Thao Hoang', 'thao.hoang@example.com', '', 'Yoga & pilates instructor', 'Ho Chi Minh City', 10.7710, 106.7090, 66, 'verified', '["verified"]', 'user', 'active', datetime('now', '-8 minutes'), datetime('now', '-30 days'), datetime('now')),
('vn_hcm_11', 'duc_ngo', 'Duc Ngo', 'duc.ngo@example.com', '', 'Startup founder | EdTech', 'Ho Chi Minh City', 10.7856, 106.6765, 88, 'highly_trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-1 minutes'), datetime('now', '-100 days'), datetime('now')),
('vn_hcm_12', 'mai_dang', 'Mai Dang', 'mai.dang@example.com', '', 'Fashion blogger & stylist', 'Ho Chi Minh City', 10.7723, 106.6945, 62, 'verified', '[]', 'user', 'active', datetime('now', '-25 minutes'), datetime('now', '-15 days'), datetime('now')),
('vn_hcm_13', 'tu_trinh', 'Tu Trinh', 'tu.trinh@example.com', '', 'Data scientist @ FPT', 'Ho Chi Minh City', 10.7901, 106.7055, 70, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-6 minutes'), datetime('now', '-70 days'), datetime('now')),
('vn_hcm_14', 'hien_vu', 'Hien Vu', 'hien.vu@example.com', '', 'Chef at a 5-star hotel', 'Ho Chi Minh City', 10.7675, 106.7130, 64, 'verified', '["verified"]', 'user', 'active', datetime('now', '-18 minutes'), datetime('now', '-40 days'), datetime('now')),
('vn_hcm_15', 'phuc_bui', 'Phuc Bui', 'phuc.bui@example.com', '', 'Photographer | Weddings & events', 'Ho Chi Minh City', 10.7834, 106.6998, 71, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-9 minutes'), datetime('now', '-55 days'), datetime('now')),
('vn_hcm_16', 'vy_lam', 'Vy Lam', 'vy.lam@example.com', '', 'Nutritionist & wellness coach', 'Ho Chi Minh City', 10.7748, 106.6882, 67, 'verified', '["verified"]', 'user', 'active', datetime('now', '-11 minutes'), datetime('now', '-33 days'), datetime('now')),
('vn_hcm_17', 'nam_luong', 'Nt Luong', 'nam.luong@example.com', '', 'Full-stack dev | Gao builder', 'Ho Chi Minh City', 10.7795, 106.6935, 90, 'highly_trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-1 minutes'), datetime('now', '-120 days'), datetime('now')),
('vn_hcm_18', 'linh_cao', 'Linh Cao', 'linh.cao@example.com', '', 'Graphic designer & brand strategist', 'Ho Chi Minh City', 10.7680, 106.7075, 59, 'verified', '[]', 'user', 'active', datetime('now', '-22 minutes'), datetime('now', '-28 days'), datetime('now')),
('vn_hcm_19', 'quang_le', 'Quang Le', 'quang.le@example.com', '', 'Architect | Sustainable design', 'Ho Chi Minh City', 10.7920, 106.6810, 73, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-14 minutes'), datetime('now', '-65 days'), datetime('now')),
('vn_hcm_20', 'hong_mai', 'Hong Mai', 'hong.mai@example.com', '', 'Accountant | Startup CFO', 'Ho Chi Minh City', 10.7863, 106.7145, 61, 'verified', '["verified"]', 'user', 'active', datetime('now', '-19 minutes'), datetime('now', '-22 days'), datetime('now')),
('vn_hcm_21', 'binh_tran', 'Binh Tran', 'binh.tran@example.com', '', 'Musician & music producer', 'Ho Chi Minh City', 10.7704, 106.6960, 56, 'verified', '[]', 'user', 'active', datetime('now', '-30 minutes'), datetime('now', '-18 days'), datetime('now')),
('vn_hcm_22', 'an_pham', 'An Pham', 'an.pham@example.com', '', 'Civil engineer | Infrastructure', 'Ho Chi Minh City', 10.7955, 106.6900, 65, 'verified', '["verified"]', 'user', 'active', datetime('now', '-16 minutes'), datetime('now', '-42 days'), datetime('now')),
('vn_hcm_23', 'chi_do', 'Chi Do', 'chi.do@example.com', '', 'Lawyer | Intellectual property', 'Ho Chi Minh City', 10.7810, 106.7060, 78, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-5 minutes'), datetime('now', '-75 days'), datetime('now')),
('vn_hcm_24', 'son_ho', 'Son Ho', 'son.ho@example.com', '', 'E-commerce seller | Shopee top seller', 'Ho Chi Minh City', 10.7635, 106.6995, 69, 'verified', '["verified"]', 'user', 'active', datetime('now', '-13 minutes'), datetime('now', '-38 days'), datetime('now')),
('vn_hcm_25', 'uyen_truong', 'Uyen Truong', 'uyen.truong@example.com', '', 'Content creator | 100k followers', 'Ho Chi Minh City', 10.7876, 106.6855, 84, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-2 minutes'), datetime('now', '-85 days'), datetime('now')),
-- Thu Duc / District 9
('vn_hcm_26', 'huy_nguyen', 'Huy Nguyen', 'huy.nguyen@example.com', '', 'AI researcher @ University', 'Ho Chi Minh City', 10.8511, 106.7719, 77, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-4 minutes'), datetime('now', '-50 days'), datetime('now')),
('vn_hcm_27', 'phuong_le', 'Phuong Le', 'phuong.le@example.com', '', 'Game developer | Unity & Unreal', 'Ho Chi Minh City', 10.8445, 106.7650, 63, 'verified', '["verified"]', 'user', 'active', datetime('now', '-17 minutes'), datetime('now', '-32 days'), datetime('now')),
('vn_hcm_28', 'tam_vo', 'Tam Vo', 'tam.vo@example.com', '', 'Mechanical engineer @ Samsung VN', 'Ho Chi Minh City', 10.8380, 106.7580, 60, 'verified', '[]', 'user', 'active', datetime('now', '-21 minutes'), datetime('now', '-27 days'), datetime('now')),
-- District 7 / Phu My Hung
('vn_hcm_29', 'nhi_doan', 'Nhi Doan', 'nhi.doan@example.com', '', 'International school teacher', 'Ho Chi Minh City', 10.7295, 106.7188, 64, 'verified', '["verified"]', 'user', 'active', datetime('now', '-10 minutes'), datetime('now', '-48 days'), datetime('now')),
('vn_hcm_30', 'cuong_dinh', 'Cuong Dinh', 'cuong.dinh@example.com', '', 'Finance manager @ Dragon Capital', 'Ho Chi Minh City', 10.7330, 106.7210, 81, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-3 minutes'), datetime('now', '-90 days'), datetime('now')),
-- Binh Thanh
('vn_hcm_31', 'truc_luu', 'Truc Luu', 'truc.luu@example.com', '', 'Social media manager', 'Ho Chi Minh City', 10.8020, 106.7110, 57, 'verified', '[]', 'user', 'active', datetime('now', '-23 minutes'), datetime('now', '-19 days'), datetime('now')),
('vn_hcm_32', 'dat_le', 'Dat Le', 'dat.le@example.com', '', 'Personal trainer | Gym owner', 'Ho Chi Minh City', 10.8055, 106.7050, 68, 'verified', '["verified"]', 'user', 'active', datetime('now', '-8 minutes'), datetime('now', '-36 days'), datetime('now')),
('vn_hcm_33', 'my_ho', 'My Ho', 'my.ho@example.com', '', 'Dentist | Cosmetic dentistry', 'Ho Chi Minh City', 10.7990, 106.7160, 75, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-6 minutes'), datetime('now', '-58 days'), datetime('now')),
('vn_hcm_34', 'khoi_tran', 'Khoi Tran', 'khoi.tran@example.com', '', 'Blockchain developer | Solana', 'Ho Chi Minh City', 10.8100, 106.7090, 71, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-4 minutes'), datetime('now', '-44 days'), datetime('now')),
('vn_hcm_35', 'ha_bui', 'Ha Bui', 'ha.bui@example.com', '', 'Veterinarian | Pet lover', 'Ho Chi Minh City', 10.7950, 106.7200, 62, 'verified', '["verified"]', 'user', 'active', datetime('now', '-15 minutes'), datetime('now', '-29 days'), datetime('now')),
-- Tan Binh / Airport area
('vn_hcm_36', 'loc_phan', 'Loc Phan', 'loc.phan@example.com', '', 'Pilot @ VietJet Air', 'Ho Chi Minh City', 10.8188, 106.6590, 70, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-12 minutes'), datetime('now', '-52 days'), datetime('now')),
('vn_hcm_37', 'thuy_ngo', 'Thuy Ngo', 'thuy.ngo@example.com', '', 'Hotel manager | Hospitality', 'Ho Chi Minh City', 10.8140, 106.6650, 66, 'verified', '[]', 'user', 'active', datetime('now', '-20 minutes'), datetime('now', '-34 days'), datetime('now')),
('vn_hcm_38', 'tien_dinh', 'Tien Dinh', 'tien.dinh@example.com', '', 'Logistics coordinator | Import/Export', 'Ho Chi Minh City', 10.8210, 106.6520, 58, 'verified', '["verified"]', 'user', 'active', datetime('now', '-28 minutes'), datetime('now', '-24 days'), datetime('now')),
('vn_hcm_39', 'anh_vu', 'Anh Vu', 'anh.vu@example.com', '', 'Interior designer | Minimalist style', 'Ho Chi Minh City', 10.7588, 106.6830, 73, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-7 minutes'), datetime('now', '-62 days'), datetime('now')),
('vn_hcm_40', 'van_nguyen', 'Van Nguyen', 'van.nguyen@example.com', '', 'Nurse | Emergency department', 'Ho Chi Minh City', 10.7555, 106.6780, 65, 'verified', '["verified"]', 'user', 'active', datetime('now', '-16 minutes'), datetime('now', '-41 days'), datetime('now'));

-- Hanoi (25 users) — Hoan Kiem, Ba Dinh, Cau Giay, Dong Da, Tay Ho
INSERT OR IGNORE INTO users (id, username, display_name, email, avatar_url, bio, city, location_lat, location_lng, trust_score, trust_level, badges, role, status, last_seen_at, created_at, updated_at) VALUES
('vn_hn_01', 'ha_le', 'Ha Le', 'ha.le@example.com', '', 'Journalist @ VnExpress', 'Hanoi', 21.0285, 105.8542, 79, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-2 minutes'), datetime('now', '-50 days'), datetime('now')),
('vn_hn_02', 'hung_tran', 'Hung Tran', 'hung.tran@example.com', '', 'Software engineer @ Grab VN', 'Hanoi', 21.0320, 105.8490, 75, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-5 minutes'), datetime('now', '-65 days'), datetime('now')),
('vn_hn_03', 'ly_nguyen', 'Ly Nguyen', 'ly.nguyen@example.com', '', 'Art curator | Contemporary art', 'Hanoi', 21.0340, 105.8520, 68, 'verified', '["verified"]', 'user', 'active', datetime('now', '-8 minutes'), datetime('now', '-38 days'), datetime('now')),
('vn_hn_04', 'son_pham', 'Son Pham', 'son.pham@example.com', '', 'Tea master & ceramic artist', 'Hanoi', 21.0260, 105.8580, 62, 'verified', '[]', 'user', 'active', datetime('now', '-15 minutes'), datetime('now', '-25 days'), datetime('now')),
('vn_hn_05', 'thao_bui', 'Thao Bui', 'thao.bui@example.com', '', 'Professor @ Hanoi University', 'Hanoi', 21.0380, 105.8350, 85, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-3 minutes'), datetime('now', '-90 days'), datetime('now')),
-- Cau Giay
('vn_hn_06', 'dat_hoang', 'Dat Hoang', 'dat.hoang@example.com', '', 'CTO @ local fintech startup', 'Hanoi', 21.0365, 105.7940, 83, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-1 minutes'), datetime('now', '-85 days'), datetime('now')),
('vn_hn_07', 'nga_do', 'Nga Do', 'nga.do@example.com', '', 'HR Director @ FPT Software', 'Hanoi', 21.0410, 105.7890, 72, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-7 minutes'), datetime('now', '-55 days'), datetime('now')),
('vn_hn_08', 'phong_le', 'Phong Le', 'phong.le@example.com', '', 'YouTuber | Tech reviews 500k subs', 'Hanoi', 21.0330, 105.7980, 77, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-4 minutes'), datetime('now', '-70 days'), datetime('now')),
('vn_hn_09', 'hoa_vu', 'Hoa Vu', 'hoa.vu@example.com', '', 'Pharmacist | Traditional medicine', 'Hanoi', 21.0450, 105.7850, 60, 'verified', '["verified"]', 'user', 'active', datetime('now', '-18 minutes'), datetime('now', '-33 days'), datetime('now')),
('vn_hn_10', 'quan_nguyen', 'Quan Nguyen', 'quan.nguyen@example.com', '', 'Civil servant | Urban planning', 'Hanoi', 21.0290, 105.8010, 64, 'verified', '[]', 'user', 'active', datetime('now', '-22 minutes'), datetime('now', '-28 days'), datetime('now')),
-- Tay Ho / West Lake
('vn_hn_11', 'linh_truong', 'Linh Truong', 'linh.truong@example.com', '', 'Expat community organizer', 'Hanoi', 21.0590, 105.8230, 74, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-3 minutes'), datetime('now', '-80 days'), datetime('now')),
('vn_hn_12', 'kien_vo', 'Kien Vo', 'kien.vo@example.com', '', 'Restaurant owner | Vietnamese cuisine', 'Hanoi', 21.0550, 105.8310, 69, 'verified', '["verified"]', 'user', 'active', datetime('now', '-10 minutes'), datetime('now', '-46 days'), datetime('now')),
('vn_hn_13', 'phuong_dinh', 'Phuong Dinh', 'phuong.dinh@example.com', '', 'Diplomat | Foreign affairs', 'Hanoi', 21.0480, 105.8190, 80, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-6 minutes'), datetime('now', '-72 days'), datetime('now')),
-- Ba Dinh
('vn_hn_14', 'tuan_lam', 'Tuan Lam', 'tuan.lam@example.com', '', 'Historian & tour guide', 'Hanoi', 21.0362, 105.8340, 63, 'verified', '["verified"]', 'user', 'active', datetime('now', '-14 minutes'), datetime('now', '-37 days'), datetime('now')),
('vn_hn_15', 'oanh_cao', 'Oanh Cao', 'oanh.cao@example.com', '', 'Pediatrician | Children hospital', 'Hanoi', 21.0400, 105.8280, 76, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-9 minutes'), datetime('now', '-60 days'), datetime('now')),
-- Dong Da
('vn_hn_16', 'vinh_phan', 'Vinh Phan', 'vinh.phan@example.com', '', 'Bookstore owner & book club host', 'Hanoi', 21.0220, 105.8320, 66, 'verified', '["verified"]', 'user', 'active', datetime('now', '-12 minutes'), datetime('now', '-42 days'), datetime('now')),
('vn_hn_17', 'ngan_ho', 'Ngan Ho', 'ngan.ho@example.com', '', 'Dance instructor | Contemporary & hip-hop', 'Hanoi', 21.0180, 105.8400, 58, 'verified', '[]', 'user', 'active', datetime('now', '-20 minutes'), datetime('now', '-20 days'), datetime('now')),
('vn_hn_18', 'hieu_bui', 'Hieu Bui', 'hieu.bui@example.com', '', 'Mechanical engineer | Automotive', 'Hanoi', 21.0150, 105.8450, 61, 'verified', '["verified"]', 'user', 'active', datetime('now', '-25 minutes'), datetime('now', '-31 days'), datetime('now')),
-- Long Bien / Gia Lam
('vn_hn_19', 'thi_le', 'Thi Le', 'thi.le@example.com', '', 'Factory manager | Electronics', 'Hanoi', 21.0470, 105.8810, 55, 'verified', '[]', 'user', 'active', datetime('now', '-28 minutes'), datetime('now', '-17 days'), datetime('now')),
('vn_hn_20', 'duc_nguyen', 'Duc Nguyen', 'duc.nguyen2@example.com', '', 'Delivery driver | Grab & GoJek', 'Hanoi', 21.0510, 105.8750, 48, 'new', '[]', 'user', 'active', datetime('now', '-2 minutes'), datetime('now', '-10 days'), datetime('now')),
-- Ha Dong
('vn_hn_21', 'lien_tran', 'Lien Tran', 'lien.tran@example.com', '', 'Primary school teacher', 'Hanoi', 20.9710, 105.7780, 63, 'verified', '["verified"]', 'user', 'active', datetime('now', '-11 minutes'), datetime('now', '-44 days'), datetime('now')),
('vn_hn_22', 'manh_do', 'Manh Do', 'manh.do@example.com', '', 'Construction foreman', 'Hanoi', 20.9780, 105.7850, 50, 'verified', '[]', 'user', 'active', datetime('now', '-30 minutes'), datetime('now', '-15 days'), datetime('now')),
('vn_hn_23', 'thu_pham', 'Thu Pham', 'thu.pham@example.com', '', 'Florist & event decorator', 'Hanoi', 21.0200, 105.8250, 67, 'verified', '["verified"]', 'user', 'active', datetime('now', '-9 minutes'), datetime('now', '-39 days'), datetime('now')),
('vn_hn_24', 'bao_vo', 'Bao Vo', 'bao.vo@example.com', '', 'Police officer | Community safety', 'Hanoi', 21.0310, 105.8600, 71, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-13 minutes'), datetime('now', '-56 days'), datetime('now')),
('vn_hn_25', 'quynh_luu', 'Quynh Luu', 'quynh.luu@example.com', '', 'Fashion designer | Ao dai modern', 'Hanoi', 21.0245, 105.8470, 73, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-6 minutes'), datetime('now', '-68 days'), datetime('now'));

-- Da Nang (15 users)
INSERT OR IGNORE INTO users (id, username, display_name, email, avatar_url, bio, city, location_lat, location_lng, trust_score, trust_level, badges, role, status, last_seen_at, created_at, updated_at) VALUES
('vn_dn_01', 'quoc_tran', 'Quoc Tran', 'quoc.tran@example.com', '', 'Surf instructor | Beach life', 'Da Nang', 16.0544, 108.2022, 65, 'verified', '["verified"]', 'user', 'active', datetime('now', '-5 minutes'), datetime('now', '-40 days'), datetime('now')),
('vn_dn_02', 'anh_le', 'Anh Le', 'anh.le@example.com', '', 'Hotel receptionist @ Hyatt', 'Da Nang', 16.0470, 108.2240, 55, 'verified', '[]', 'user', 'active', datetime('now', '-12 minutes'), datetime('now', '-25 days'), datetime('now')),
('vn_dn_03', 'trung_nguyen', 'Trung Nguyen', 'trung.nguyen@example.com', '', 'Seafood restaurant owner', 'Da Nang', 16.0680, 108.2180, 72, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-3 minutes'), datetime('now', '-55 days'), datetime('now')),
('vn_dn_04', 'hoa_pham', 'Hoa Pham', 'hoa.pham@example.com', '', 'Tour guide | Ba Na Hills specialist', 'Da Nang', 16.0410, 108.2100, 60, 'verified', '["verified"]', 'user', 'active', datetime('now', '-8 minutes'), datetime('now', '-33 days'), datetime('now')),
('vn_dn_05', 'khoa_bui', 'Khoa Bui', 'khoa.bui@example.com', '', 'Digital nomad | Remote SWE', 'Da Nang', 16.0590, 108.2350, 78, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-1 minutes'), datetime('now', '-70 days'), datetime('now')),
('vn_dn_06', 'nhu_vo', 'Nhu Vo', 'nhu.vo@example.com', '', 'Scuba diving instructor | PADI certified', 'Da Nang', 16.0350, 108.2450, 63, 'verified', '["verified"]', 'user', 'active', datetime('now', '-15 minutes'), datetime('now', '-28 days'), datetime('now')),
('vn_dn_07', 'loi_dinh', 'Loi Dinh', 'loi.dinh@example.com', '', 'Fisherman & boat tour captain', 'Da Nang', 16.0750, 108.2280, 52, 'verified', '[]', 'user', 'active', datetime('now', '-25 minutes'), datetime('now', '-18 days'), datetime('now')),
('vn_dn_08', 'thu_hoang', 'Thu Hoang', 'thu.hoang@example.com', '', 'Real estate agent | Beach properties', 'Da Nang', 16.0510, 108.2150, 66, 'verified', '["verified"]', 'user', 'active', datetime('now', '-10 minutes'), datetime('now', '-42 days'), datetime('now')),
('vn_dn_09', 'vinh_le', 'Vinh Le', 'vinh.le@example.com', '', 'Civil engineer | Bridge construction', 'Da Nang', 16.0620, 108.2050, 60, 'verified', '[]', 'user', 'active', datetime('now', '-18 minutes'), datetime('now', '-35 days'), datetime('now')),
('vn_dn_10', 'mai_nguyen', 'Mai Nguyen', 'mai.nguyen2@example.com', '', 'Kindergarten teacher | Art therapy', 'Da Nang', 16.0440, 108.1980, 58, 'verified', '["verified"]', 'user', 'active', datetime('now', '-20 minutes'), datetime('now', '-22 days'), datetime('now')),
('vn_dn_11', 'tuan_phan', 'Tuan Phan', 'tuan.phan@example.com', '', 'Motorbike mechanic & customizer', 'Da Nang', 16.0700, 108.2120, 54, 'verified', '[]', 'user', 'active', datetime('now', '-28 minutes'), datetime('now', '-14 days'), datetime('now')),
('vn_dn_12', 'lan_dang', 'Lan Dang', 'lan.dang@example.com', '', 'Nurse at Da Nang Hospital', 'Da Nang', 16.0560, 108.2000, 64, 'verified', '["verified"]', 'user', 'active', datetime('now', '-14 minutes'), datetime('now', '-47 days'), datetime('now')),
('vn_dn_13', 'nam_ho', 'Nam Ho', 'nam.ho@example.com', '', 'Coffee shop owner | Specialty beans', 'Da Nang', 16.0480, 108.2090, 68, 'verified', '["verified"]', 'user', 'active', datetime('now', '-7 minutes'), datetime('now', '-51 days'), datetime('now')),
('vn_dn_14', 'huyen_tran', 'Huyen Tran', 'huyen.tran@example.com', '', 'Yoga retreat organizer', 'Da Nang', 16.0390, 108.2300, 70, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-6 minutes'), datetime('now', '-60 days'), datetime('now')),
('vn_dn_15', 'dung_le', 'Dung Le', 'dung.le@example.com', '', 'Photographer | Landscape & travel', 'Da Nang', 16.0660, 108.2400, 62, 'verified', '["verified"]', 'user', 'active', datetime('now', '-9 minutes'), datetime('now', '-36 days'), datetime('now'));

-- Other cities (20 users) — Hue, Nha Trang, Can Tho, Hai Phong, Vung Tau
INSERT OR IGNORE INTO users (id, username, display_name, email, avatar_url, bio, city, location_lat, location_lng, trust_score, trust_level, badges, role, status, last_seen_at, created_at, updated_at) VALUES
-- Hue (4)
('vn_hue_01', 'minh_pham', 'Minh Pham', 'minh.pham2@example.com', '', 'History teacher | Imperial city guide', 'Hue', 16.4637, 107.5909, 67, 'verified', '["verified"]', 'user', 'active', datetime('now', '-5 minutes'), datetime('now', '-40 days'), datetime('now')),
('vn_hue_02', 'thanh_le', 'Thanh Le', 'thanh.le2@example.com', '', 'Traditional music performer', 'Hue', 16.4700, 107.5850, 58, 'verified', '[]', 'user', 'active', datetime('now', '-15 minutes'), datetime('now', '-28 days'), datetime('now')),
('vn_hue_03', 'kim_nguyen', 'Kim Nguyen', 'kim.nguyen@example.com', '', 'Bun bo Hue chef | Family recipe', 'Hue', 16.4580, 107.5960, 63, 'verified', '["verified"]', 'user', 'active', datetime('now', '-10 minutes'), datetime('now', '-45 days'), datetime('now')),
('vn_hue_04', 'hien_tran', 'Hien Tran', 'hien.tran@example.com', '', 'Garden designer | Tropical plants', 'Hue', 16.4550, 107.6000, 55, 'verified', '[]', 'user', 'active', datetime('now', '-22 minutes'), datetime('now', '-20 days'), datetime('now')),
-- Nha Trang (4)
('vn_nt_01', 'hai_bui', 'Hai Bui', 'hai.bui@example.com', '', 'Diving center owner | Coral conservation', 'Nha Trang', 12.2388, 109.1967, 74, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-3 minutes'), datetime('now', '-60 days'), datetime('now')),
('vn_nt_02', 'ngoc_vo', 'Ngoc Vo', 'ngoc.vo@example.com', '', 'Resort spa manager', 'Nha Trang', 12.2450, 109.1900, 60, 'verified', '["verified"]', 'user', 'active', datetime('now', '-12 minutes'), datetime('now', '-35 days'), datetime('now')),
('vn_nt_03', 'tung_pham', 'Tung Pham', 'tung.pham@example.com', '', 'Kitesurfing instructor', 'Nha Trang', 12.2520, 109.2030, 56, 'verified', '[]', 'user', 'active', datetime('now', '-18 minutes'), datetime('now', '-22 days'), datetime('now')),
('vn_nt_04', 'diep_le', 'Diep Le', 'diep.le@example.com', '', 'Travel blogger | 200k followers', 'Nha Trang', 12.2310, 109.1880, 71, 'trusted', '["verified","active_community"]', 'user', 'active', datetime('now', '-2 minutes'), datetime('now', '-75 days'), datetime('now')),
-- Can Tho (4)
('vn_ct_01', 'hoa_nguyen', 'Hoa Nguyen', 'hoa.nguyen2@example.com', '', 'Rice farmer & agri-tech pioneer', 'Can Tho', 10.0452, 105.7469, 65, 'verified', '["verified"]', 'user', 'active', datetime('now', '-8 minutes'), datetime('now', '-48 days'), datetime('now')),
('vn_ct_02', 'phuc_tran', 'Phuc Tran', 'phuc.tran2@example.com', '', 'Floating market boat operator', 'Can Tho', 10.0380, 105.7520, 52, 'verified', '[]', 'user', 'active', datetime('now', '-20 minutes'), datetime('now', '-18 days'), datetime('now')),
('vn_ct_03', 'lien_pham', 'Lien Pham', 'lien.pham@example.com', '', 'University lecturer | Agriculture', 'Can Tho', 10.0510, 105.7410, 70, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-6 minutes'), datetime('now', '-55 days'), datetime('now')),
('vn_ct_04', 'sang_vo', 'Sang Vo', 'sang.vo@example.com', '', 'Fish sauce maker | 3rd generation', 'Can Tho', 10.0420, 105.7550, 59, 'verified', '["verified"]', 'user', 'active', datetime('now', '-14 minutes'), datetime('now', '-32 days'), datetime('now')),
-- Hai Phong (4)
('vn_hp_01', 'cuong_le', 'Cuong Le', 'cuong.le2@example.com', '', 'Port logistics manager', 'Hai Phong', 20.8449, 106.6881, 68, 'verified', '["verified"]', 'user', 'active', datetime('now', '-7 minutes'), datetime('now', '-43 days'), datetime('now')),
('vn_hp_02', 'huong_do', 'Huong Do', 'huong.do@example.com', '', 'Seafood exporter | Cat Ba island', 'Hai Phong', 20.8380, 106.6950, 62, 'verified', '[]', 'user', 'active', datetime('now', '-16 minutes'), datetime('now', '-30 days'), datetime('now')),
('vn_hp_03', 'tam_nguyen', 'Tam Nguyen', 'tam.nguyen@example.com', '', 'Ship engineer | Maritime', 'Hai Phong', 20.8510, 106.6810, 57, 'verified', '["verified"]', 'user', 'active', datetime('now', '-24 minutes'), datetime('now', '-26 days'), datetime('now')),
('vn_hp_04', 'yen_bui', 'Yen Bui', 'yen.bui@example.com', '', 'Baker | French-Vietnamese pastries', 'Hai Phong', 20.8420, 106.6920, 64, 'verified', '["verified"]', 'user', 'active', datetime('now', '-11 minutes'), datetime('now', '-50 days'), datetime('now')),
-- Vung Tau (4)
('vn_vt_01', 'thien_tran', 'Thien Tran', 'thien.tran@example.com', '', 'Oil rig engineer | Offshore', 'Vung Tau', 10.3460, 107.0843, 72, 'trusted', '["verified"]', 'user', 'active', datetime('now', '-4 minutes'), datetime('now', '-58 days'), datetime('now')),
('vn_vt_02', 'trinh_phan', 'Trinh Phan', 'trinh.phan@example.com', '', 'Beach resort owner', 'Vung Tau', 10.3520, 107.0780, 66, 'verified', '["verified"]', 'user', 'active', datetime('now', '-13 minutes'), datetime('now', '-38 days'), datetime('now')),
('vn_vt_03', 'bich_le', 'Bich Le', 'bich.le@example.com', '', 'Retired teacher | Painting hobbyist', 'Vung Tau', 10.3400, 107.0900, 54, 'verified', '[]', 'user', 'active', datetime('now', '-26 minutes'), datetime('now', '-16 days'), datetime('now')),
('vn_vt_04', 'hoai_nguyen', 'Hoai Nguyen', 'hoai.nguyen@example.com', '', 'Windsurfer & beach bar owner', 'Vung Tau', 10.3550, 107.0720, 60, 'verified', '["verified"]', 'user', 'active', datetime('now', '-9 minutes'), datetime('now', '-44 days'), datetime('now'));

-- ── Profiles for all VN users (so they show on map) ────────────────────
-- HCM profiles
INSERT OR IGNORE INTO profiles (id, user_id, headline, bio, industry, skills, experience, education, languages, lat, lng, city, available, work_type, trust_score_snapshot, status, created_at, updated_at) VALUES
('prof_hcm_01', 'vn_hcm_01', 'Mobile Developer | Flutter & RN', 'Building cross-platform apps', 'Technology', '["Flutter","React Native","Dart","TypeScript"]', '[]', '[]', '["Vietnamese","English"]', 10.7731, 106.7030, 'Ho Chi Minh City', 1, 'hybrid', 72, 'active', datetime('now', '-40 days'), datetime('now')),
('prof_hcm_02', 'vn_hcm_02', 'Marketing Manager @ Shopee', 'Growth & performance marketing', 'Marketing', '["SEO","SEM","Social Media","Analytics"]', '[]', '[]', '["Vietnamese","English"]', 10.7815, 106.6993, 'Ho Chi Minh City', 1, 'onsite', 80, 'active', datetime('now', '-55 days'), datetime('now')),
('prof_hcm_05', 'vn_hcm_05', 'Backend Engineer @ VNG', 'Distributed systems & Go', 'Technology', '["Go","Kubernetes","PostgreSQL","Redis"]', '[]', '[]', '["Vietnamese","English"]', 10.7698, 106.6914, 'Ho Chi Minh City', 1, 'onsite', 76, 'active', datetime('now', '-60 days'), datetime('now')),
('prof_hcm_06', 'vn_hcm_06', 'Product Designer | Figma', 'Design systems & prototyping', 'Design', '["Figma","Sketch","Design Systems","User Research"]', '[]', '[]', '["Vietnamese","English"]', 10.7889, 106.6851, 'Ho Chi Minh City', 1, 'remote', 82, 'active', datetime('now', '-80 days'), datetime('now')),
('prof_hcm_11', 'vn_hcm_11', 'Startup Founder | EdTech', 'Building the future of education in SEA', 'Education', '["Product","Strategy","Fundraising","Leadership"]', '[]', '[]', '["Vietnamese","English"]', 10.7856, 106.6765, 'Ho Chi Minh City', 1, 'hybrid', 88, 'active', datetime('now', '-100 days'), datetime('now')),
('prof_hcm_17', 'vn_hcm_17', 'Full-Stack Dev | Gao Builder', 'Next.js, TypeScript, MapLibre', 'Technology', '["Next.js","TypeScript","React","Node.js","MapLibre"]', '[]', '[]', '["Vietnamese","English"]', 10.7795, 106.6935, 'Ho Chi Minh City', 1, 'remote', 90, 'active', datetime('now', '-120 days'), datetime('now')),
('prof_hcm_26', 'vn_hcm_26', 'AI Researcher', 'NLP & computer vision', 'Technology', '["Python","PyTorch","NLP","Computer Vision"]', '[]', '[]', '["Vietnamese","English"]', 10.8511, 106.7719, 'Ho Chi Minh City', 1, 'hybrid', 77, 'active', datetime('now', '-50 days'), datetime('now')),
-- Hanoi profiles
('prof_hn_01', 'vn_hn_01', 'Journalist @ VnExpress', 'Investigative reporting', 'Media', '["Writing","Research","Interviewing","Editing"]', '[]', '[]', '["Vietnamese","English"]', 21.0285, 105.8542, 'Hanoi', 1, 'hybrid', 79, 'active', datetime('now', '-50 days'), datetime('now')),
('prof_hn_06', 'vn_hn_06', 'CTO @ Fintech Startup', 'Building payment infrastructure', 'Technology', '["System Design","Java","Microservices","Fintech"]', '[]', '[]', '["Vietnamese","English"]', 21.0365, 105.7940, 'Hanoi', 1, 'hybrid', 83, 'active', datetime('now', '-85 days'), datetime('now')),
('prof_hn_08', 'vn_hn_08', 'Tech YouTuber | 500k subs', 'Reviews & tutorials', 'Media', '["Video Production","Content","Tech Reviews"]', '[]', '[]', '["Vietnamese","English"]', 21.0330, 105.7980, 'Hanoi', 1, 'remote', 77, 'active', datetime('now', '-70 days'), datetime('now')),
-- Da Nang profiles
('prof_dn_05', 'vn_dn_05', 'Digital Nomad SWE', 'Remote work from the beach', 'Technology', '["React","Node.js","AWS","Remote Work"]', '[]', '[]', '["Vietnamese","English"]', 16.0590, 108.2350, 'Da Nang', 1, 'remote', 78, 'active', datetime('now', '-70 days'), datetime('now')),
('prof_dn_13', 'vn_dn_13', 'Coffee Shop Owner', 'Specialty beans & brewing', 'Food & Beverage', '["Coffee","Roasting","Business","Hospitality"]', '[]', '[]', '["Vietnamese","English"]', 16.0480, 108.2090, 'Da Nang', 1, 'onsite', 68, 'active', datetime('now', '-51 days'), datetime('now'));
