-- ============================================================================
-- Gao Social V3 — Seed Businesses & Events across Vietnam
-- Run after seed-local.sql and seed-users-vn.sql
-- ============================================================================

-- ── Businesses — HCM (20) ──────────────────────────────────────────────
INSERT OR IGNORE INTO businesses (id, owner_user_id, name, category, description, location_lat, location_lng, address, city, phone, hours, booking_enabled, cover_image, images, services, subcategories, trust_score, trust_level, badges, rating_avg, rating_count, proof_count, status, created_at, updated_at) VALUES
('biz_vn_01', 'vn_hcm_03', 'Highlands Coffee D1', 'Food & Drink', 'Popular Vietnamese coffee chain. Phin filter coffee, freeze drinks.', 10.7735, 106.7015, '10 Dong Khoi, District 1', 'Ho Chi Minh City', '+84 28 1111 2222', '{}', 1, '', '[]', '[]', '["Coffee","Tea"]', 70, 'trusted', '["verified"]', 4.3, 245, 30, 'active', datetime('now', '-50 days'), datetime('now')),
('biz_vn_02', 'vn_hcm_10', 'Golden Lotus Spa', 'Health & Fitness', 'Traditional Vietnamese massage. Herbal steam, hot stone therapy.', 10.7788, 106.6925, '25 Thai Van Lung, D1', 'Ho Chi Minh City', '+84 28 3333 4444', '{}', 1, '', '[]', '[]', '["Spa","Massage","Wellness"]', 65, 'verified', '["verified"]', 4.7, 89, 12, 'active', datetime('now', '-40 days'), datetime('now')),
('biz_vn_03', 'vn_hcm_12', 'Saigon Boutique Fashion', 'Shopping', 'Modern Vietnamese fashion. Ao dai, contemporary design, custom tailoring.', 10.7755, 106.6988, '55 Le Thanh Ton, D1', 'Ho Chi Minh City', '+84 28 5555 6666', '{}', 0, '', '[]', '[]', '["Fashion","Ao Dai","Tailoring"]', 58, 'verified', '[]', 4.5, 67, 8, 'active', datetime('now', '-35 days'), datetime('now')),
('biz_vn_04', 'vn_hcm_14', 'Pho 24 Ben Thanh', 'Food & Drink', 'Authentic pho bo and pho ga. Quick service, clean environment.', 10.7725, 106.6980, '24 Le Lai, D1', 'Ho Chi Minh City', '+84 28 7777 8888', '{}', 0, '', '[]', '[]', '["Pho","Vietnamese","Noodles"]', 62, 'verified', '["verified"]', 4.2, 312, 55, 'active', datetime('now', '-70 days'), datetime('now')),
('biz_vn_05', 'vn_hcm_09', 'DevOps Academy VN', 'Education', 'Cloud computing courses. AWS, Docker, Kubernetes bootcamp.', 10.7860, 106.6870, '88 CMT8, District 3', 'Ho Chi Minh City', '+84 28 9999 0000', '{}', 1, '', '[]', '[]', '["Education","Cloud","DevOps"]', 75, 'trusted', '["verified","active_community"]', 4.8, 42, 6, 'active', datetime('now', '-80 days'), datetime('now')),
('biz_vn_06', 'vn_hcm_15', 'Click Studio Photography', 'Services', 'Professional photography. Weddings, portraits, product shoots.', 10.7830, 106.6998, '15 Vo Van Tan, D3', 'Ho Chi Minh City', '+84 28 1234 0000', '{}', 1, '', '[]', '[]', '["Photography","Weddings","Portraits"]', 68, 'verified', '["verified"]', 4.6, 55, 10, 'active', datetime('now', '-30 days'), datetime('now')),
('biz_vn_07', 'vn_hcm_21', 'Saigon Sound Studio', 'Entertainment', 'Professional recording studio. Music production, mixing, mastering.', 10.7705, 106.6955, '78 Nguyen Trai, D5', 'Ho Chi Minh City', '+84 28 4444 3333', '{}', 1, '', '[]', '[]', '["Music","Recording","Production"]', 60, 'verified', '[]', 4.4, 28, 5, 'active', datetime('now', '-25 days'), datetime('now')),
('biz_vn_08', 'vn_hcm_30', 'PMH Pet Clinic', 'Health & Fitness', 'Full-service veterinary clinic. Vaccinations, surgery, grooming.', 10.7310, 106.7200, '12 Nguyen Luong Bang, D7', 'Ho Chi Minh City', '+84 28 5555 7777', '{}', 1, '', '[]', '[]', '["Veterinary","Pets","Grooming"]', 72, 'trusted', '["verified"]', 4.9, 110, 20, 'active', datetime('now', '-60 days'), datetime('now')),
('biz_vn_09', 'vn_hcm_26', 'Innovation Lab Thu Duc', 'Services', 'AI research lab & incubator. Startup mentoring, GPU cluster rental.', 10.8500, 106.7700, '1 Vo Chi Cong, Thu Duc', 'Ho Chi Minh City', '+84 28 8888 9999', '{}', 1, '', '[]', '[]', '["AI","Startup","Lab"]', 80, 'trusted', '["verified","active_community"]', 4.7, 35, 8, 'active', datetime('now', '-90 days'), datetime('now')),
('biz_vn_10', 'vn_hcm_32', 'Iron Gym Binh Thanh', 'Health & Fitness', 'Hardcore gym. Powerlifting, CrossFit, personal training.', 10.8040, 106.7060, '200 Dien Bien Phu, Binh Thanh', 'Ho Chi Minh City', '+84 28 2222 1111', '{}', 1, '', '[]', '[]', '["Gym","CrossFit","Powerlifting"]', 66, 'verified', '["verified"]', 4.5, 78, 14, 'active', datetime('now', '-45 days'), datetime('now')),
-- HCM District 1 cluster
('biz_vn_11', 'vn_hcm_04', 'Sketch Design Studio', 'Services', 'UI/UX design agency. Branding, web design, mobile apps.', 10.7770, 106.6990, '30 Hai Ba Trung, D1', 'Ho Chi Minh City', '', '{}', 0, '', '[]', '[]', '["Design","Branding","UX"]', 74, 'trusted', '["verified"]', 4.6, 33, 7, 'active', datetime('now', '-55 days'), datetime('now')),
('biz_vn_12', 'vn_hcm_06', 'Book Worm Cafe', 'Food & Drink', 'Cozy bookstore cafe. Great pastries, quiet atmosphere, 500+ books.', 10.7785, 106.7025, '18 Nguyen Du, D1', 'Ho Chi Minh City', '', '{}', 0, '', '[]', '[]', '["Books","Coffee","Cafe"]', 55, 'verified', '[]', 4.4, 92, 11, 'active', datetime('now', '-28 days'), datetime('now')),
('biz_vn_13', 'vn_hcm_16', 'Green Smoothie Bar', 'Food & Drink', 'Cold-pressed juices, smoothie bowls, plant-based snacks.', 10.7745, 106.6940, '5 Ly Tu Trong, D1', 'Ho Chi Minh City', '', '{}', 0, '', '[]', '[]', '["Smoothies","Healthy","Vegan"]', 50, 'verified', '[]', 4.3, 120, 15, 'active', datetime('now', '-20 days'), datetime('now'));

-- ── Businesses — Hanoi (10) ────────────────────────────────────────────
INSERT OR IGNORE INTO businesses (id, owner_user_id, name, category, description, location_lat, location_lng, address, city, phone, hours, booking_enabled, cover_image, images, services, subcategories, trust_score, trust_level, badges, rating_avg, rating_count, proof_count, status, created_at, updated_at) VALUES
('biz_vn_20', 'vn_hn_04', 'Egg Coffee Original', 'Food & Drink', 'Famous Hanoi egg coffee. Family recipe since 1946.', 21.0315, 105.8525, '11 Hang Gai, Hoan Kiem', 'Hanoi', '', '{}', 0, '', '[]', '[]', '["Coffee","Traditional"]', 85, 'trusted', '["verified","popular"]', 4.9, 520, 80, 'active', datetime('now', '-100 days'), datetime('now')),
('biz_vn_21', 'vn_hn_12', 'Pho Thin Legend', 'Food & Drink', 'Iconic Hanoi pho. Rich beef broth, fresh herbs, 60 years of perfection.', 21.0340, 105.8500, '13 Lo Duc, Hai Ba Trung', 'Hanoi', '', '{}', 0, '', '[]', '[]', '["Pho","Vietnamese","Noodles"]', 80, 'trusted', '["verified","popular"]', 4.8, 890, 120, 'active', datetime('now', '-120 days'), datetime('now')),
('biz_vn_22', 'vn_hn_06', 'Codebase Coworking', 'Services', 'Premium coworking for developers. Fast fiber, standing desks, meeting rooms.', 21.0370, 105.7930, '50 Cau Giay', 'Hanoi', '', '{}', 1, '', '[]', '[]', '["Coworking","Tech","Startup"]', 78, 'trusted', '["verified","active_community"]', 4.7, 48, 9, 'active', datetime('now', '-75 days'), datetime('now')),
('biz_vn_23', 'vn_hn_15', 'Little Stars Pediatrics', 'Health & Fitness', 'Friendly pediatric clinic. Vaccinations, checkups, emergency care.', 21.0395, 105.8290, '8 Kim Ma, Ba Dinh', 'Hanoi', '', '{}', 1, '', '[]', '[]', '["Pediatrics","Healthcare","Children"]', 82, 'trusted', '["verified"]', 4.8, 75, 15, 'active', datetime('now', '-65 days'), datetime('now')),
('biz_vn_24', 'vn_hn_11', 'West Lake Paddle Board', 'Entertainment', 'SUP rental on West Lake. Sunset tours, yoga on water.', 21.0580, 105.8250, 'West Lake promenade, Tay Ho', 'Hanoi', '', '{}', 1, '', '[]', '[]', '["SUP","Water Sports","Tours"]', 60, 'verified', '["verified"]', 4.5, 55, 8, 'active', datetime('now', '-30 days'), datetime('now')),
('biz_vn_25', 'vn_hn_03', 'Hanoi Art Gallery', 'Entertainment', 'Contemporary Vietnamese art. Exhibitions, workshops, art sales.', 21.0300, 105.8540, '45 Trang Tien, Hoan Kiem', 'Hanoi', '', '{}', 0, '', '[]', '[]', '["Art","Gallery","Exhibitions"]', 70, 'trusted', '["verified"]', 4.6, 38, 5, 'active', datetime('now', '-50 days'), datetime('now')),
('biz_vn_26', 'vn_hn_16', 'Old Quarter Books', 'Shopping', 'Used & new bookstore. English, Vietnamese, French literature.', 21.0330, 105.8510, '5 Dinh Liet, Hoan Kiem', 'Hanoi', '', '{}', 0, '', '[]', '[]', '["Books","Literature"]', 55, 'verified', '[]', 4.4, 62, 7, 'active', datetime('now', '-40 days'), datetime('now')),
('biz_vn_27', 'vn_hn_17', 'Beat Street Dance', 'Entertainment', 'Hip-hop & contemporary dance studio. Classes for all levels.', 21.0200, 105.8380, '22 Kham Thien, Dong Da', 'Hanoi', '', '{}', 1, '', '[]', '[]', '["Dance","Hip-hop","Classes"]', 58, 'verified', '["verified"]', 4.5, 44, 6, 'active', datetime('now', '-22 days'), datetime('now')),
('biz_vn_28', 'vn_hn_08', 'TechReview Studio', 'Services', 'YouTube production studio. Tech reviews, content creation.', 21.0335, 105.7970, '15 Tran Duy Hung, Cau Giay', 'Hanoi', '', '{}', 1, '', '[]', '[]', '["YouTube","Content","Production"]', 72, 'trusted', '["verified"]', 4.6, 25, 4, 'active', datetime('now', '-35 days'), datetime('now')),
('biz_vn_29', 'vn_hn_14', 'Hanoi Heritage Walks', 'Services', 'Walking tours of old quarter, French quarter, temples.', 21.0350, 105.8530, '2 Hang Bac, Hoan Kiem', 'Hanoi', '', '{}', 1, '', '[]', '[]', '["Tours","History","Walking"]', 68, 'verified', '["verified"]', 4.7, 180, 35, 'active', datetime('now', '-85 days'), datetime('now'));

-- ── Businesses — Da Nang (8) ───────────────────────────────────────────
INSERT OR IGNORE INTO businesses (id, owner_user_id, name, category, description, location_lat, location_lng, address, city, phone, hours, booking_enabled, cover_image, images, services, subcategories, trust_score, trust_level, badges, rating_avg, rating_count, proof_count, status, created_at, updated_at) VALUES
('biz_vn_40', 'vn_dn_03', 'Seafood King Da Nang', 'Food & Drink', 'Fresh seafood restaurant on My Khe beach. Live tanks, ocean view.', 16.0600, 108.2450, 'My Khe Beach Rd', 'Da Nang', '', '{}', 1, '', '[]', '[]', '["Seafood","Restaurant","Beach"]', 75, 'trusted', '["verified","popular"]', 4.6, 280, 45, 'active', datetime('now', '-80 days'), datetime('now')),
('biz_vn_41', 'vn_dn_06', 'Deep Blue Dive Center', 'Entertainment', 'PADI certified dive center. Scuba, snorkeling, Cham Islands tours.', 16.0370, 108.2430, '55 Vo Nguyen Giap', 'Da Nang', '', '{}', 1, '', '[]', '[]', '["Diving","Snorkeling","Tours"]', 72, 'trusted', '["verified"]', 4.8, 95, 18, 'active', datetime('now', '-60 days'), datetime('now')),
('biz_vn_42', 'vn_dn_05', 'Nomad Coffee & Work', 'Food & Drink', 'Digital nomad cafe. Fast wifi, power outlets, quiet zones.', 16.0560, 108.2320, '12 An Thuong 4', 'Da Nang', '', '{}', 0, '', '[]', '[]', '["Coffee","Coworking","Nomad"]', 68, 'verified', '["verified","active_community"]', 4.5, 65, 10, 'active', datetime('now', '-40 days'), datetime('now')),
('biz_vn_43', 'vn_dn_13', 'Da Nang Specialty Coffee', 'Food & Drink', 'Single origin Vietnamese beans. Pour-over, cold brew, roasting workshops.', 16.0490, 108.2080, '8 Bach Dang', 'Da Nang', '', '{}', 0, '', '[]', '[]', '["Coffee","Specialty","Roasting"]', 66, 'verified', '["verified"]', 4.7, 48, 7, 'active', datetime('now', '-45 days'), datetime('now')),
('biz_vn_44', 'vn_dn_14', 'Sunrise Yoga Retreat', 'Health & Fitness', 'Beachfront yoga. Sunrise sessions, meditation, wellness retreats.', 16.0400, 108.2300, 'An Bang Beach Rd', 'Da Nang', '', '{}', 1, '', '[]', '[]', '["Yoga","Meditation","Retreat"]', 70, 'trusted', '["verified"]', 4.8, 55, 10, 'active', datetime('now', '-55 days'), datetime('now')),
('biz_vn_45', 'vn_dn_01', 'Wave Rider Surf School', 'Entertainment', 'Surf lessons for all levels. Board rental, surf camp packages.', 16.0550, 108.2480, 'My Khe Beach', 'Da Nang', '', '{}', 1, '', '[]', '[]', '["Surfing","Lessons","Beach"]', 64, 'verified', '["verified"]', 4.6, 72, 12, 'active', datetime('now', '-35 days'), datetime('now')),
('biz_vn_46', 'vn_dn_08', 'Beach Villa Realty', 'Services', 'Beach property sales & rentals. Villas, apartments, land.', 16.0520, 108.2140, '20 Tran Phu', 'Da Nang', '', '{}', 0, '', '[]', '[]', '["Real Estate","Villas","Beach"]', 62, 'verified', '[]', 4.3, 30, 5, 'active', datetime('now', '-25 days'), datetime('now')),
('biz_vn_47', 'vn_dn_11', 'Moto Custom Shop', 'Services', 'Custom motorcycle builds & repairs. Vintage restorations.', 16.0680, 108.2100, '45 Le Duan', 'Da Nang', '', '{}', 1, '', '[]', '[]', '["Motorcycle","Custom","Repair"]', 56, 'verified', '[]', 4.4, 38, 6, 'active', datetime('now', '-20 days'), datetime('now'));

-- ── Businesses — Other cities (6) ──────────────────────────────────────
INSERT OR IGNORE INTO businesses (id, owner_user_id, name, category, description, location_lat, location_lng, address, city, phone, hours, booking_enabled, cover_image, images, services, subcategories, trust_score, trust_level, badges, rating_avg, rating_count, proof_count, status, created_at, updated_at) VALUES
('biz_vn_60', 'vn_nt_01', 'Nha Trang Dive Academy', 'Entertainment', 'PADI 5-star dive center. Whale shark tours, advanced certifications.', 12.2400, 109.1950, '62 Tran Phu, Nha Trang', 'Nha Trang', '', '{}', 1, '', '[]', '[]', '["Diving","PADI","Tours"]', 78, 'trusted', '["verified","popular"]', 4.9, 150, 30, 'active', datetime('now', '-90 days'), datetime('now')),
('biz_vn_61', 'vn_hue_03', 'Hue Royal Cuisine', 'Food & Drink', 'Traditional Hue imperial dishes. Bun bo Hue, banh khoai, nem lui.', 16.4620, 107.5930, '15 Nguyen Tri Phuong, Hue', 'Hue', '', '{}', 1, '', '[]', '[]', '["Vietnamese","Imperial","Traditional"]', 74, 'trusted', '["verified"]', 4.7, 200, 35, 'active', datetime('now', '-70 days'), datetime('now')),
('biz_vn_62', 'vn_ct_01', 'Mekong Float Tours', 'Entertainment', 'Floating market tours. Sampan boats, fruit tasting, cooking class.', 10.0400, 105.7500, 'Cai Rang Market, Can Tho', 'Can Tho', '', '{}', 1, '', '[]', '[]', '["Tours","Floating Market","Mekong"]', 70, 'trusted', '["verified"]', 4.6, 85, 15, 'active', datetime('now', '-65 days'), datetime('now')),
('biz_vn_63', 'vn_hp_04', 'Hai Phong Bakery', 'Food & Drink', 'French-Vietnamese pastries. Banh pateso, croissants, banh mi.', 20.8430, 106.6910, '10 Dien Bien Phu, HP', 'Hai Phong', '', '{}', 0, '', '[]', '[]', '["Bakery","Pastries","French"]', 58, 'verified', '["verified"]', 4.5, 95, 12, 'active', datetime('now', '-40 days'), datetime('now')),
('biz_vn_64', 'vn_vt_02', 'Beach Bar Vung Tau', 'Food & Drink', 'Beachfront cocktail bar. Live music weekends, sunset happy hour.', 10.3510, 107.0800, 'Back Beach Rd, Vung Tau', 'Vung Tau', '', '{}', 0, '', '[]', '[]', '["Bar","Cocktails","Live Music"]', 62, 'verified', '[]', 4.4, 110, 18, 'active', datetime('now', '-30 days'), datetime('now')),
('biz_vn_65', 'vn_nt_04', 'Nha Trang Photo Tours', 'Services', 'Instagram-worthy photo tours. Beaches, temples, hidden gems.', 12.2350, 109.1900, '5 Hung Vuong, Nha Trang', 'Nha Trang', '', '{}', 1, '', '[]', '[]', '["Photography","Tours","Instagram"]', 64, 'verified', '["verified"]', 4.6, 60, 10, 'active', datetime('now', '-35 days'), datetime('now'));

-- ── Events — HCM (10) ──────────────────────────────────────────────────
INSERT OR IGNORE INTO events (id, title, description, circle_id, host_user_id, start_time, end_time, location_name, location_lat, location_lng, city, capacity, joined_count, visibility, status, verified, created_at, updated_at) VALUES
('evt_vn_01', 'HCMC Tech Meetup #42', 'Monthly tech talks. This month: AI agents in production. Pizza & beer.', 'circle_seed_01', 'vn_hcm_11', datetime('now', '+3 hours'), datetime('now', '+6 hours'), 'Tech Hub Coworking', 10.7820, 106.6980, 'Ho Chi Minh City', 60, 35, 'public', 'scheduled', 1, datetime('now', '-2 days'), datetime('now')),
('evt_vn_02', 'Saigon Coffee Cupping', 'Taste 6 single-origin Vietnamese coffees. Learn brewing methods.', 'circle_seed_03', 'vn_hcm_03', datetime('now', '+1 day'), datetime('now', '+1 day', '+2 hours'), 'Highlands Coffee D1', 10.7735, 106.7015, 'Ho Chi Minh City', 20, 14, 'public', 'scheduled', 1, datetime('now', '-4 days'), datetime('now')),
('evt_vn_03', 'District 1 Photography Walk', 'Golden hour street photography. Bring your camera, any level welcome.', NULL, 'vn_hcm_15', datetime('now', '+2 days'), datetime('now', '+2 days', '+3 hours'), 'Notre-Dame Cathedral', 10.7798, 106.6990, 'Ho Chi Minh City', 15, 10, 'public', 'scheduled', 0, datetime('now', '-1 day'), datetime('now')),
('evt_vn_04', 'React Vietnam Conference', 'Full-day conference. 12 speakers, workshops, networking. Early bird tickets.', 'circle_seed_01', 'vn_hcm_05', datetime('now', '+7 days'), datetime('now', '+7 days', '+8 hours'), 'GEM Center', 10.7810, 106.7030, 'Ho Chi Minh City', 200, 145, 'public', 'scheduled', 1, datetime('now', '-14 days'), datetime('now')),
('evt_vn_05', 'Sunset Yoga at Landmark 81', 'Rooftop yoga session at sunset. All levels. Mats provided.', 'circle_seed_04', 'vn_hcm_10', datetime('now', '+1 day', '+9 hours'), datetime('now', '+1 day', '+10 hours'), 'Landmark 81 Rooftop', 10.7952, 106.7219, 'Ho Chi Minh City', 30, 22, 'public', 'scheduled', 1, datetime('now', '-3 days'), datetime('now')),
('evt_vn_06', 'Saigon Night Market Food Tour', 'Guided food tour through Ben Thanh Night Market. 10 tastings included.', 'circle_seed_03', 'vn_hcm_14', datetime('now', '-1 hour'), datetime('now', '+2 hours'), 'Ben Thanh Market', 10.7725, 106.6980, 'Ho Chi Minh City', 12, 12, 'public', 'live', 1, datetime('now', '-5 days'), datetime('now')),
('evt_vn_07', 'Blockchain Builder Bootcamp', '3-day intensive. Build a DApp from scratch. Solidity + React.', 'circle_seed_02', 'vn_hcm_34', datetime('now', '+5 days'), datetime('now', '+7 days'), 'Innovation Lab Thu Duc', 10.8500, 106.7700, 'Ho Chi Minh City', 25, 18, 'public', 'scheduled', 1, datetime('now', '-7 days'), datetime('now')),
('evt_vn_08', 'PMH International Brunch', 'Monthly expat brunch. International food, live jazz, networking.', NULL, 'vn_hcm_29', datetime('now', '+3 days', '+4 hours'), datetime('now', '+3 days', '+7 hours'), 'Phu My Hung Park', 10.7300, 106.7195, 'Ho Chi Minh City', 40, 28, 'public', 'scheduled', 0, datetime('now', '-2 days'), datetime('now')),
('evt_vn_09', 'Saigon Indie Music Night', 'Live indie bands. 4 acts, outdoor stage. BYOB friendly.', NULL, 'vn_hcm_21', datetime('now', '+4 days', '+12 hours'), datetime('now', '+4 days', '+16 hours'), 'Saigon Sound Studio', 10.7705, 106.6955, 'Ho Chi Minh City', 80, 55, 'public', 'scheduled', 0, datetime('now', '-3 days'), datetime('now')),
('evt_vn_10', 'UX Design Workshop', 'Hands-on Figma workshop. Design a mobile app in 4 hours.', 'circle_seed_01', 'vn_hcm_06', datetime('now', '+6 days'), datetime('now', '+6 days', '+4 hours'), 'Sketch Design Studio', 10.7770, 106.6990, 'Ho Chi Minh City', 20, 16, 'public', 'scheduled', 1, datetime('now', '-5 days'), datetime('now'));

-- ── Events — Hanoi (8) ─────────────────────────────────────────────────
INSERT OR IGNORE INTO events (id, title, description, circle_id, host_user_id, start_time, end_time, location_name, location_lat, location_lng, city, capacity, joined_count, visibility, status, verified, created_at, updated_at) VALUES
('evt_vn_20', 'Hanoi AI Hackathon', '48-hour hackathon. Build AI-powered apps. $5000 prize pool.', NULL, 'vn_hn_06', datetime('now', '+2 days'), datetime('now', '+4 days'), 'Codebase Coworking', 21.0370, 105.7930, 'Hanoi', 100, 72, 'public', 'scheduled', 1, datetime('now', '-10 days'), datetime('now')),
('evt_vn_21', 'Old Quarter Night Food Walk', 'Authentic Hanoi street food tour. Bun cha, banh cuon, egg coffee.', NULL, 'vn_hn_12', datetime('now', '+1 day', '+11 hours'), datetime('now', '+1 day', '+14 hours'), 'Dong Xuan Market', 21.0380, 105.8500, 'Hanoi', 12, 10, 'public', 'scheduled', 1, datetime('now', '-3 days'), datetime('now')),
('evt_vn_22', 'West Lake Sunset SUP', 'Stand-up paddleboard at sunset. Beginners welcome. Boards provided.', NULL, 'vn_hn_11', datetime('now', '+2 days', '+10 hours'), datetime('now', '+2 days', '+12 hours'), 'West Lake SUP Point', 21.0580, 105.8250, 'Hanoi', 16, 12, 'public', 'scheduled', 0, datetime('now', '-2 days'), datetime('now')),
('evt_vn_23', 'Hanoi Book Club', 'Monthly meeting. This month: "The Sympathizer" by Viet Thanh Nguyen.', NULL, 'vn_hn_16', datetime('now', '+5 days', '+8 hours'), datetime('now', '+5 days', '+10 hours'), 'Old Quarter Books', 21.0330, 105.8510, 'Hanoi', 15, 9, 'public', 'scheduled', 0, datetime('now', '-4 days'), datetime('now')),
('evt_vn_24', 'Vietnamese Traditional Music Night', 'Live ca tru & dan tranh performance. Tea service included.', NULL, 'vn_hue_02', datetime('now', '+3 days', '+12 hours'), datetime('now', '+3 days', '+14 hours'), 'Hanoi Art Gallery', 21.0300, 105.8540, 'Hanoi', 40, 25, 'public', 'scheduled', 1, datetime('now', '-6 days'), datetime('now')),
('evt_vn_25', 'Fintech Vietnam Summit', 'Full-day fintech conference. Payment innovations, digital banking.', NULL, 'vn_hn_06', datetime('now', '+10 days'), datetime('now', '+10 days', '+8 hours'), 'JW Marriott Hanoi', 21.0020, 105.8030, 'Hanoi', 300, 180, 'public', 'scheduled', 1, datetime('now', '-14 days'), datetime('now')),
('evt_vn_26', 'Cau Giay Running Club', 'Weekly 5K/10K run. All paces welcome. Coffee after at Codebase.', NULL, 'vn_hn_07', datetime('now', '+1 day', '+3 hours'), datetime('now', '+1 day', '+4 hours'), 'Cau Giay Park', 21.0380, 105.7920, 'Hanoi', 30, 18, 'public', 'scheduled', 0, datetime('now', '-1 day'), datetime('now')),
('evt_vn_27', 'Hip Hop Dance Battle', 'Monthly dance battle. Prizes for top 3. Open registration.', NULL, 'vn_hn_17', datetime('now', '+6 days', '+13 hours'), datetime('now', '+6 days', '+17 hours'), 'Beat Street Dance', 21.0200, 105.8380, 'Hanoi', 50, 35, 'public', 'scheduled', 0, datetime('now', '-5 days'), datetime('now'));

-- ── Events — Da Nang (5) ───────────────────────────────────────────────
INSERT OR IGNORE INTO events (id, title, description, circle_id, host_user_id, start_time, end_time, location_name, location_lat, location_lng, city, capacity, joined_count, visibility, status, verified, created_at, updated_at) VALUES
('evt_vn_40', 'Da Nang Beach Cleanup', 'Community beach cleanup. Gloves & bags provided. Lunch after.', NULL, 'vn_dn_06', datetime('now', '+2 days', '+4 hours'), datetime('now', '+2 days', '+7 hours'), 'My Khe Beach', 16.0580, 108.2460, 'Da Nang', 50, 32, 'public', 'scheduled', 1, datetime('now', '-3 days'), datetime('now')),
('evt_vn_41', 'Nomad Networking Night', 'Monthly meetup for digital nomads. Share tips, find coliving partners.', NULL, 'vn_dn_05', datetime('now', '+4 days', '+12 hours'), datetime('now', '+4 days', '+15 hours'), 'Nomad Coffee & Work', 16.0560, 108.2320, 'Da Nang', 30, 22, 'public', 'scheduled', 0, datetime('now', '-5 days'), datetime('now')),
('evt_vn_42', 'Sunrise Yoga & Meditation', 'Beach yoga at 5:30am. Meditation session after. Free for first-timers.', NULL, 'vn_dn_14', datetime('now', '+1 day', '+22 hours'), datetime('now', '+2 days', '+0 hours'), 'An Bang Beach', 16.0400, 108.2300, 'Da Nang', 20, 15, 'public', 'scheduled', 1, datetime('now', '-2 days'), datetime('now')),
('evt_vn_43', 'Seafood Cooking Class', 'Learn to cook Vietnamese seafood dishes. Market tour + 3-course meal.', NULL, 'vn_dn_03', datetime('now', '+3 days', '+5 hours'), datetime('now', '+3 days', '+8 hours'), 'Seafood King Da Nang', 16.0600, 108.2450, 'Da Nang', 10, 8, 'public', 'scheduled', 1, datetime('now', '-4 days'), datetime('now')),
('evt_vn_44', 'Full Moon Party Da Nang', 'Beachfront party. DJ sets, fire show, cocktails. Monthly tradition.', NULL, 'vn_dn_01', datetime('now', '+8 days', '+13 hours'), datetime('now', '+9 days'), 'My Khe Beach South', 16.0500, 108.2420, 'Da Nang', 200, 120, 'public', 'scheduled', 0, datetime('now', '-7 days'), datetime('now'));

-- ── Events — Other cities (4) ──────────────────────────────────────────
INSERT OR IGNORE INTO events (id, title, description, circle_id, host_user_id, start_time, end_time, location_name, location_lat, location_lng, city, capacity, joined_count, visibility, status, verified, created_at, updated_at) VALUES
('evt_vn_60', 'Nha Trang Dive Festival', '3-day diving festival. Coral planting, night dives, conservation talks.', NULL, 'vn_nt_01', datetime('now', '+5 days'), datetime('now', '+7 days'), 'Nha Trang Dive Academy', 12.2400, 109.1950, 'Nha Trang', 80, 55, 'public', 'scheduled', 1, datetime('now', '-10 days'), datetime('now')),
('evt_vn_61', 'Hue Imperial Food Festival', 'Annual food festival. 50+ stalls, cooking demos, cultural performances.', NULL, 'vn_hue_03', datetime('now', '+12 days'), datetime('now', '+14 days'), 'Imperial Citadel', 16.4700, 107.5850, 'Hue', 500, 280, 'public', 'scheduled', 1, datetime('now', '-20 days'), datetime('now')),
('evt_vn_62', 'Can Tho Floating Market Sunrise', 'Early morning boat tour. Buy fruit directly from farmers on water.', NULL, 'vn_ct_02', datetime('now', '+1 day', '+21 hours'), datetime('now', '+2 days', '+0 hours'), 'Cai Rang Floating Market', 10.0380, 105.7520, 'Can Tho', 8, 6, 'public', 'scheduled', 1, datetime('now', '-2 days'), datetime('now')),
('evt_vn_63', 'Vung Tau Kitesurfing Camp', '5-day kitesurfing camp. Equipment provided, accommodation included.', NULL, 'vn_vt_04', datetime('now', '+15 days'), datetime('now', '+20 days'), 'Long Hai Beach', 10.3550, 107.0720, 'Vung Tau', 12, 7, 'public', 'scheduled', 0, datetime('now', '-8 days'), datetime('now'));
