import { create } from 'zustand';
import type { Developer } from '@/types';

interface DeveloperStore {
  developers: Developer[];
  showOnMap: boolean;
  toggleShowOnMap: () => void;
}

const SEED_DEVELOPERS: Developer[] = [
  {
    id: 'dev_1',
    display_name: 'Luong Nguyen',
    gao_domain: 'luong.gao',
    title: 'Founder & Full-Stack Architect',
    bio: 'Building Gao Internet — 8-layer sovereign internet stack. Expert in React, Next.js, Node.js, AI/ML, blockchain. Passionate about decentralized systems and privacy-first products.',
    skills: ['React', 'Next.js', 'TypeScript', 'Node.js', 'Solidity', 'AI/ML', 'MapLibre', 'PostgreSQL', 'MongoDB', 'Redis'],
    experience_years: 10,
    location_city: 'Dallas, TX',
    location: { type: 'Point', coordinates: [-96.797, 32.777] },
    is_available: false,
    trust_score: 98,
    trust_level: 'highly_trusted',
    badges: ['verified_identity'],
    work_history: [
      { company: 'Toii Labs', role: 'Founder & CEO', period: '2023 — Present' },
      { company: 'Tech Startup', role: 'CTO', period: '2020 — 2023' },
      { company: 'Enterprise Corp', role: 'Senior Engineer', period: '2016 — 2020' },
    ],
    education: [{ school: 'University of Technology', degree: 'BS Computer Science', year: '2016' }],
    languages: ['English', 'Vietnamese'],
  },
  {
    id: 'dev_2',
    display_name: 'Sofia Martinez',
    gao_domain: 'sofia.gao',
    title: 'Senior Frontend Engineer',
    bio: 'UI/UX specialist with deep React & design system expertise. Built products for 2M+ users. Love crafting beautiful, accessible interfaces.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Figma', 'Framer Motion', 'Next.js', 'Storybook', 'a11y'],
    experience_years: 7,
    location_city: 'San Francisco, CA',
    location: { type: 'Point', coordinates: [-122.419, 37.775] },
    is_available: true,
    rate_per_hour: 150,
    currency: 'USDC',
    portfolio_url: 'https://sofia.design',
    github_url: 'https://github.com/sofia',
    trust_score: 85,
    trust_level: 'highly_trusted',
    badges: ['verified_identity', 'trusted_member'],
    work_history: [
      { company: 'Stripe', role: 'Senior Frontend Engineer', period: '2021 — 2024' },
      { company: 'Figma', role: 'Frontend Engineer', period: '2019 — 2021' },
      { company: 'Startup Inc', role: 'UI Developer', period: '2017 — 2019' },
    ],
    education: [{ school: 'Stanford', degree: 'MS HCI', year: '2017' }],
    languages: ['English', 'Spanish'],
  },
  {
    id: 'dev_3',
    display_name: 'Kenji Yamamoto',
    gao_domain: 'kenji.gao',
    title: 'Blockchain & Smart Contract Engineer',
    bio: 'Solidity expert, built DeFi protocols with $500M+ TVL. Audited 30+ smart contracts. Focused on security-first development.',
    skills: ['Solidity', 'Rust', 'EVM', 'DeFi', 'Security Audit', 'Foundry', 'Hardhat', 'Zero Knowledge'],
    experience_years: 6,
    location_city: 'Tokyo, Japan',
    location: { type: 'Point', coordinates: [139.691, 35.689] },
    is_available: true,
    rate_per_hour: 200,
    currency: 'USDC',
    github_url: 'https://github.com/kenji',
    trust_score: 90,
    trust_level: 'highly_trusted',
    badges: ['verified_identity', 'trusted_seller'],
    work_history: [
      { company: 'Aave', role: 'Smart Contract Engineer', period: '2022 — 2024' },
      { company: 'Uniswap Labs', role: 'Protocol Engineer', period: '2020 — 2022' },
    ],
    education: [{ school: 'University of Tokyo', degree: 'MS Computer Science', year: '2018' }],
    languages: ['English', 'Japanese'],
  },
  {
    id: 'dev_4',
    display_name: 'Priya Sharma',
    gao_domain: 'priya.gao',
    title: 'AI/ML Engineer',
    bio: 'Building intelligent systems with LLMs, computer vision, and NLP. Published researcher. Contributed to open-source AI frameworks.',
    skills: ['Python', 'PyTorch', 'LLMs', 'RAG', 'Computer Vision', 'NLP', 'FastAPI', 'Kubernetes'],
    experience_years: 5,
    location_city: 'Bangalore, India',
    location: { type: 'Point', coordinates: [77.594, 12.972] },
    is_available: true,
    rate_per_hour: 100,
    currency: 'USDC',
    github_url: 'https://github.com/priya',
    trust_score: 78,
    trust_level: 'trusted',
    badges: ['verified_identity'],
    work_history: [
      { company: 'Google DeepMind', role: 'Research Engineer', period: '2022 — 2024' },
      { company: 'Hugging Face', role: 'ML Engineer', period: '2020 — 2022' },
    ],
    education: [{ school: 'IIT Bangalore', degree: 'MS AI/ML', year: '2019' }],
    languages: ['English', 'Hindi'],
  },
  {
    id: 'dev_5',
    display_name: 'Marcus Johnson',
    gao_domain: 'marcus.gao',
    title: 'DevOps & Infrastructure Engineer',
    bio: 'Cloud-native infrastructure specialist. Kubernetes, Terraform, CI/CD at scale. Reduced infra costs by 60% at previous company.',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'GCP', 'Docker', 'CI/CD', 'Monitoring', 'Rust'],
    experience_years: 8,
    location_city: 'London, UK',
    location: { type: 'Point', coordinates: [-0.118, 51.509] },
    is_available: true,
    rate_per_hour: 175,
    currency: 'USDC',
    trust_score: 82,
    trust_level: 'trusted',
    badges: ['verified_identity'],
    work_history: [
      { company: 'Cloudflare', role: 'Senior SRE', period: '2021 — 2024' },
      { company: 'Spotify', role: 'DevOps Engineer', period: '2018 — 2021' },
      { company: 'ThoughtWorks', role: 'Infrastructure Consultant', period: '2016 — 2018' },
    ],
    languages: ['English'],
  },
  {
    id: 'dev_6',
    display_name: 'Ana Costa',
    gao_domain: 'ana.gao',
    title: 'Mobile & React Native Engineer',
    bio: 'Shipped 10+ apps on App Store & Play Store. Specializing in cross-platform mobile with React Native and Flutter.',
    skills: ['React Native', 'Flutter', 'iOS', 'Android', 'TypeScript', 'Firebase', 'GraphQL'],
    experience_years: 6,
    location_city: 'São Paulo, Brazil',
    location: { type: 'Point', coordinates: [-46.633, -23.550] },
    is_available: true,
    rate_per_hour: 90,
    currency: 'USDC',
    portfolio_url: 'https://ana.dev',
    trust_score: 70,
    trust_level: 'trusted',
    badges: [],
    work_history: [
      { company: 'Nubank', role: 'Senior Mobile Engineer', period: '2022 — 2024' },
      { company: 'iFood', role: 'React Native Developer', period: '2019 — 2022' },
    ],
    education: [{ school: 'USP', degree: 'BS Software Engineering', year: '2018' }],
    languages: ['English', 'Portuguese'],
  },
];

export const useDeveloperStore = create<DeveloperStore>((set) => ({
  developers: SEED_DEVELOPERS,
  showOnMap: false,
  toggleShowOnMap: () => set((s) => ({ showOnMap: !s.showOnMap })),
}));
